### ISSUE TITLE
Everlasting Items

### ISSUE THREAD

**Issue by Fortist** [ochotonida/artifacts#1]
While, I think you can get away with just having One (1) everlasting food item, (Isnt there a mod that adds an apple? I dont remember)
There is a slight hiccup with the raw versions, at least with just one mod.
When you throw any of them into an augmented TE Redstone Furnace, you can get double the output.
![2019-02-06_19 39 46](https://user-images.githubusercontent.com/5784537/52383873-2861fb80-2a49-11e9-9061-5d3ea292555d.png)

I dont actually think this is a problem of this mod, but I'd go back to my original point and say I think you can get away with just one everlasting food item.
But I think after checking the loot tables you cant actually get them just yet.

**Comment by ochotonida** [comment]
This is something I didn't think of, but I'll probably be able to fix this. As for the loot tables, I didn't add the items to the loot tables because a weight of 1 would still be too high. You can actually get them, but I'll see if there's some way of adding them to Not Enough Resources
