### ISSUE TITLE
[Suggestion] Config option to change how flower pots are generated

### ISSUE THREAD

**Issue by StaticSapphic** [ochotonida/artifacts#103]
Currently the campsites can generate with a flower pot that contains _any_  valid flower pot plant item, which can include sequence breaking items like nether wart (quark) and twilight forest trees. 

A config option could be added to allow modpack creators to blacklist/whitelist certain flower pot items, or to restrict to only vanilla plant pot items.

![javaw_mf9ZqKKndN](https://user-images.githubusercontent.com/30599923/125979172-6d3dcc7e-422e-4558-a107-3ab557c4389a.png)
![javaw_8qdzD3vG80](https://user-images.githubusercontent.com/30599923/125979189-71d8539a-221b-464b-a689-1df6c9bab4ff.png)

**Comment by ochotonida** [comment]
I've decided to just restrict the flower pots to vanilla plants only. Doing it with a config option would be a bit more effort than it's worth, especially considering I'll likely completely redo world gen in this mod once 1.18 rolls around.
