### ISSUE TITLE
Mining Ores from the "Ore Stone Variants" mod while equipping the Lucky Scarf causes the blocks to drop coal

### ISSUE THREAD

**Issue by tharrmeehan** [ochotonida/artifacts#104]
**Describe the bug**
Mining ores generated by the "Ore Stone Variants" mod (https://www.curseforge.com/minecraft/mc-mods/ore-stone-variants) while wearing a Lucky Scarf causes every mined block from said mod to turn into coal. I'm not sure if this is a bug caused by Artifcats though.
Reverts when unequpping the lucky scarf.
![image](https://user-images.githubusercontent.com/58373200/127186057-057228ff-3aab-440c-b12f-9e1b1836e248.png)

**To Reproduce**
1. Download both mods
2. Create a new world
3. Equip Lucky scarf into curios slot
4. Go mine a block generated from OSV
5. Coal gets dropped

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: latest (
Artifacts-1.16.5-2.10.0.)
 - Forge: 36.2.0
 - Ore Stone Variants

**Comment by tharrmeehan** [comment]
You'll also need OptiFine to properly load the textures from OSV

https://user-images.githubusercontent.com/58373200/127190528-d1cf0b40-274f-43ea-84b7-1f3452aa5f2d.mp4

**Comment by ochotonida** [comment]
This seems to be an issue on Ore Stone Variants' end, I've relayed it to their issue tracker (see linked issue).
