### ISSUE TITLE
Stuck items

### ISSUE THREAD

**Issue by distressedflower** [ochotonida/artifacts#106]
I have been using Valhelsia 3 and in it is this artifacts mod. Most everything has worked just fine
Until the Whoopie cushion. After using it, it became stuck on my head, even when out of my inventory it is still stuck! 
I was wondering if there is a reason for this, it's not in my belt slot or any other slot for that matter....
thank you for the help

**Comment by ochotonida** [comment]
This is an issue with Curious Armor Stands, I fixed it a while ago but it seems worlds created before the patch are still affected (I'm not sure if there's anything I can do about that). You can fix it using the following command: `/curios lock armor_stand_curio <player>`
