### ISSUE TITLE
 An option in the config to set the cooldown for the Everlasting Beef

### ISSUE THREAD

**Issue by Gillios** [ochotonida/artifacts#107]
Hey, it would be great if you could set the cooldown of the Everlasting Beef in a config. It's nice when you drop it, but it takes so long to be usable again. Or install it so that the hunger is completely replenished.

**Comment by florensie** [comment]
There's been a config for this for a very long time now. I think might be called "Everlasting Food cooldown", it should be in the server configs.

**Comment by Gillios** [comment]
I use this Version 
Artifacts-1.16.5-2.10.0.jar

and the only Config file i got is the Common one. there is nothing with the Food inside. 


#Affects how common artifacts are (does not affect mimics)
#When this is 1, the default artifact spawn rates will be used
#Values higher that 1 will decrease spawn rates while values lower than 1 will increase spawn rates
#Doubling this value will (roughly) halve the chance a container contains an artifact
#Setting this to 10000 will completely prevent artifacts from spawning
#When set to 0, every container that can contain artifacts will contain an artifact
#Range: 0.0 ~ 10000.0
artifact_rarity = 0.0

[campsite]
	#List of biome IDs in which campsites are not allowed to generate
	#End and nether biomes are excluded by default
	#To blacklist all biomes from a single mod, use "modid:*"
	biome_blacklist = ["minecraft:void", "undergarden:*", "the_bumblezone:*", "twilightforest:*"]
	#Rarity of campsites generating in the world
	#The chance a campsite generates in a specific chunk is 1/rarity
	#A rarity of 1 will generate a campsite in every chunk, while 10000 will generate no campsites
	#Not every attempt at generating a campsite succeeds, this also depends on the density and shape of caves
	#Range: 1 ~ 10000
	rarity = 12
	#The minimum y-level at which a campsite can generate
	#Range: 1 ~ 255
	min_y = 1
	#The maximum y-level at which a campsite can generate
	#Range: 1 ~ 255
	max_y = 45
	#Probability for a container of a campsite to be replaced by a mimic
	#Range: 0.0 ~ 1.0
	mimic_chance = 0.3
	#Probability for an ore vein to generate underneath a campsite
	#Range: 0.0 ~ 1.0
	ore_chance = 0.25
	#Whether to use wooden chests from other mods when generating campsites
	#(keeping this enabled may make it easier to distinguish them from mimics)
	use_modded_chests = true



this is all, not more.

**Comment by ochotonida** [comment]
Server config files can be found in your save folder (If you have Create installed it's easier to use their in-game configuration menu)
