### ISSUE TITLE
[Bug] Duplication possible of any bauble in the mod.

### ISSUE THREAD

**Issue by elucent** [ochotonida/artifacts#11]
Mod Version: 1.12.2-1.1.0
Sidedness: Multiplayer
Description: One of my players has reported and demonstrated the ability to duplicate items from your mod, with the following information:
"Press F to hold the item in your offhand, then right click to equip. The code to equip deletes whatever item is in your selected slot and adds the item right clicked to the proper bauble slot, but if its in your offhand the item isnt deleted, whatever else is instead."

The mod list of our current pack can be found at modlister.com/elucent

**Comment by wootaboot** [comment]
Yes this is definitely a problem, when you have in offhand it deletes whatever item you have in your mainhand when equip from offhand. seems like an easy fix though. just have it delete from off hand when equiping from offhand
