### ISSUE TITLE
Minecraft doesn't like Mary Poppins!

### ISSUE THREAD

**Issue by xenoflot** [ochotonida/artifacts#110]
**Describe the bug**
Falling a long distance with the Umbrella can result in being kicked for too long.

I have now set flying=true but since most jetpack mods don't seem to require this (I think!) perhaps there are checks that can be done to avoid the vanilla flying check.

**To Reproduce**
1. Find a call hill
2. Have the Umbrella in the off hand
3. Jump
4. Get kicked for flying

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: Artifacts-1.16.5-2.10.0
 - Forge: 31.1.66
 - [other relevant mods...]

**Comment by florensie** [comment]
@ochotonida https://github.com/florensie/ExpandAbility/blob/48aba94bfe57fce0be825ad0fd9597bda6cef9a8/common/src/main/java/be/florens/expandability/mixin/swimming/server/ServerGamePacketListenerImplMixin.java#L23

Forge might have an event for this as well.

**Comment by xenoflot** [comment]
Thanks, Ochotonida!
