### ISSUE TITLE
New version of Artifacts crashes on startup 

### ISSUE THREAD

**Issue by WFPhantom** [ochotonida/artifacts#112]
I'm trying to make a modpack for me and my friends to play. It worked fine but after updating Artifacts the game would crash on startup. Game would start normally after I remove Artifacts.

Steps to reproduce the behaviour:
1. Update Artifact to the latest version
2. Start Minecraft
3. Game crashes

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: 2.10.1
 - Forge: 36.2.5
(for other relevant mods I understand dependencies if you need anything else lmk)
- ExpandAbility: 2.0.1
- Curios API: 4.0.5.3

log: https://pastebin.com/sNCWARPm

**Comment by ochotonida** [comment]
There seems to be an issue with mixins which is causing the mod to crash outside of my development environment. I've temporarily archived the file on curseforge as I don't have the time to fix it right now (it's only a minor patch, so it's not really that big of an issue)

**Comment by florensie** [comment]
Looks like the refmap isn't being added to the compiled jar anymore. My best guess is that this is a side effect of the recent ForgeGradle upgrade.

**Comment by florensie** [comment]
Check Gradle buildscript settings here:
https://github.com/SpongePowered/Mixin/wiki/Mixins-on-Minecraft-Forge
https://darkhax.net/2020/07/mixins

**Comment by florensie** [comment]
Fixed in aa473983b7ba9af9f0b737bafe01d7cc0812abd1
