### ISSUE TITLE
New Artifact suggestion: Chest's soul

### ISSUE THREAD

**Issue by pantsguyapp** [ochotonida/artifacts#115]
What does it do: This artifact is a unique, as it isn't used on the player, but is used to turn your chest into a companion buddy.
How to find it: Similar to every other artifacts in the mod.
Details: This artifact is a consumable and will vanish after one use. Apply this artifact to a regular vanilla single chest under a full moon during mid-night to turn that chest into life.
Unlike the hostile mimics found underground, your tamed "trunk" is much more "tamer" and calmer in nature. You can order the trunk to sit or follow via shift-right click, and right-click to access its inventory. Your tamed chest buddy will travel with you around, albeit they do not fight mobs. You can heal them with wood planks of all types.
Optional: If struct by lightning, the chest will gain basically invulnerability as well as more inventory spaces.

This idea was inspired from the Traveling trunk in Thaumcraft 4, the lightning part is from Openblocks' Luggage.

**Comment by florensie** [comment]
I don't really think it's a good fit for this mod and it would probably take too much work to add anyways.

Other than that, there's too much hidden mechanics in there which is bad game design: "apply to vanilla single chest under full moon during midnight". How do you expect players to figure that out?

Also as you said, it's been done before and there might even be mods on more recent versions of Minecraft that have this.

**Comment by ochotonida** [comment]
I agree that it's not really a good fit for the mod. It's a bit too complex in terms of functionality when compared to the other artifacts. I generally try to keep the items in this mod simple enough that you can start using them immediately after reading the tooltip, which is usually a single sentence.
