### ISSUE TITLE
Artifacts Loot Table Gone Awry 

### ISSUE THREAD

**Issue by RobertHDPotatoes** [ochotonida/artifacts#117]
**Describe the bug**
Artifacts only generate in campsite chests, the vanilla chests they are supposed to generate in are completely empty, and Artifacts fills my log file with:

"Couldn't parse loot table minecraft:chests/****/****
java.lang.RuntimeException: Attempted to add a duplicate pool to loot table: artifacts_inject" 

I replaced the direct path of the loot table with stars because it's a LOT of loot tables that come up, not just one. It also adds dozens of lines of errors in my log for each loot table, not just those two lines. I simply copy & pasted only that part in particular. As a side note, because of the parsing errors I physically cannot upload my log files to pastebin because they are too large. Sorry.

I believe this is actually related to issue 44, which was closed a while ago (https://github.com/ochotonida/artifacts/issues/44). It seems that this is not considered an issue because another mod could be the one actually causing the problem. In issue 44 two separate people each had a different mod that caused this issue (ChanceCubes and WyrmRoost), and I don't have either of those mods so I guess there are at least three mods that cause this issue. However, even in that thread, it seems that if you disable Artifacts, the loot table parsing errors cease. I also have this outcome. I was simply wondering if it's at all possible to revisit this issue and possibly fix it? If not, is there a possible solution for me, without having to go through my 200 mods to figure out where the incompatibility is?

**To Reproduce**
Install Artifacts
Install Nameless Trinkets
do /setblock ~ ~ ~-1 minecraft:chest{LootTable:"minecraft:chests/desert_pyramid"}
Chest is empty, and log file is showing errors.

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: 1.16.5-2.10.3
 - Forge: 36.2.9
 - Here's a download link to my latest log: https://www.dropbox.com/s/mmmkbg9jts4mvpy/latest.log?dl=0

**Comment by RobertHDPotatoes** [comment]
Found the incompatibility, it's with a mod called Nameless Trinkets, which is similar and also generates curios in similar chests. Incase it's a problem on their side, I will report this issue to that mod creator and link it to them as well.

**Comment by ochotonida** [comment]
Thanks for the detailed report! This issue seems to be entirely on Nameless Trinkets' side. They are reusing quite a bit of code from Artifacts, and as a result they forgot to pick a unique name for their injected loot pools.
Once 1.18 rolls around I'll see if I can use Forge's global loot modifiers to add loot to chests. They are a bit more robust than the loot table injects I'm currently using, which should prevent issues like this and #44.
