### ISSUE TITLE
Vampiric glove only heals if you deal 10 damage after armor reductions by default

### ISSUE THREAD

**Issue by Jackiecrazy** [ochotonida/artifacts#118]
So in vanilla, only a crit with diamond+ gear (or enchanted iron gear, or with power gloves) on a nearly unarmored target would heal, because anything less will be reduced by armor and divided by 10, likely placing its value below the cutoff line of 1. Is this intentional? Health is a float value, and the actual function seems to be different from the tooltip description.

**Comment by ochotonida** [comment]
The default absorption rate of the vampiric glove is 25% damage dealt, so you actually only need to deal 4 damage or more, not 10. I do agree that the cutoff might be a bit confusing, and doesn't work very well when the absorption rate is configured to be lower than the default value. I'll release a patch to remove the cutoff and slightly reduce the default absorption rate instead.

**Comment by Jackiecrazy** [comment]
Ah, yeah, sorry, I was reading the config off a custom modpack. Still, the amount is 25% of the damage after armor reductions, which may be confusing. I guess it's fine if the default is adjusted to remove the cutoff point.

**Comment by ochotonida** [comment]
I've uploaded a patch that addresses this issue
