### ISSUE TITLE
Can you see if this issue is being caused by your mod?

### ISSUE THREAD

**Issue by Sunconure11** [ochotonida/artifacts#12]
https://paste.dimdev.org/zikexofawi.mccrash

**Comment by ochotonida** [comment]
Very unlikely. At first impression it seems to be caused or at least related to malisis core/malisis doors, check if removing it helps

**Comment by Sunconure11** [comment]
I tried that in the past, but that did not seem to stop the issue. A player ran into it again, so I'm having him playtest to see if the issue is still present after he pulls artifacts.

**Comment by Sunconure11** [comment]
I had also reported said error to them, if it was them, but got no response.

https://github.com/Ordinastie/MalisisDoors/issues/311
