### ISSUE TITLE
Drop Rate

### ISSUE THREAD

**Issue by Valentinovik** [ochotonida/artifacts#121]
Cows drop too many Endless steaks.

**To Reproduce**
-Kill a cow , you have a really high chance of getting a endless beef in 1 or 2 cows

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
I did check the config file but i dont see anything that changes the drop rate from cows.
 - Artifacts: [4.0.0]
 - Forge: [39.0.7]
 - [Minecraft 1.18.1]

**Comment by ochotonida** [comment]
This issue has been fixed in Artifacts 4.0.1
