### ISSUE TITLE
[1.18.1] [Feature] LootR compatibility

### ISSUE THREAD

**Issue by ArchieBeepBoop** [ochotonida/artifacts#126]
**This is technically a feature request but I'm not sure if this is not intended or not, so I'm posting it with the bug report guidelines regardless.**

**The request itself is to have the mod be more compatible with LootR, although I'm not sure as to how this can be achieved. What I do know however is that the artifact drop rate plummets when using LootR.**

=========================
**Describe the bug**
When used with LootR, the drop rates for artifacts plummet down severely. I decided to test this in singleplayer and after spawning in several LootR chests, only a single artifact dropped. 

**To Reproduce**
1. Install LootR and Artifacts

2. Spawn lootR chests with /lootr chest or /lootr barrel

3. Verify rates

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: artifacts-1.18.1-4.0.2
 - Lootr: lootr-1.18-0.1.13.40.jar
 - Forge: 1.18.1-39.0.10

**Comment by ochotonida** [comment]
Thanks for the report/suggestion!

Unfortunately I can't seem to be able to recreate this issue. Lootr doesn't affect which items appear in chests as far as I'm aware. After spawning 100 lootr chests with the abandoned mineshaft loot table, I got an artifact in 34 of them, which is pretty close to the actual drop rate for that loot table (30%).

Were you using any mods other than lootr and artifacts when performing your test, and/or did you modify the artifact rarity in the common config? Also, which loot table(s) did you use to test this? Not every chest can contain artifacts.

**Comment by ArchieBeepBoop** [comment]
Ah, I used random chests that are spawned simply by using /lootr chest
I thought the artifacts mod injected its artifacts into every loot table, so that must be why it didn't quite work. The reduced artifact drop could've been placebo then, but I'm not quite sure.

**Comment by ochotonida** [comment]
That probably explains it. If it seems like you're still having issues feel free to either create a new issue or reopen this one, although it's unlikely it would be directly caused by Artifacts or Lootr
