### ISSUE TITLE
Incompatibility with Automatic Tool Swap

### ISSUE THREAD

**Issue by Ceimnithe** [ochotonida/artifacts#127]
Noticed my toolswap mod wasn't working properly anymore, it would actually switch off of the proper tool rather than the correct one when Artifacts was installed. I.e mining stone with a pickaxe will cause my hotbar to swap off of my pickaxe, usually to an empty hand or torch. Tried messing with toolswap config and eliminating other mods before I realized Artifacts was the problem, now I'm just stunned lol. Any suggestions appreciated :)

Minecraft 1.18.1
Artifacts 4.0.2
Tool Swap 3.0.1 - https://www.curseforge.com/minecraft/mc-mods/automatic-tool-swap/files/3595871
Forge 39.0.76 (As of writing this, I stay up to date)

**Comment by ochotonida** [comment]
Thanks for the report! After some investigation, this seems to be an issue with Automatic Tool Swap rather than Artifacts. I've relayed the issue here: https://github.com/MelanX/ToolSwap/issues/27#issuecomment-1041836667
