### ISSUE TITLE
[1.16.5] When player sleeps with umbrella in hand, the world shakes every tick/frame.

### ISSUE THREAD

**Issue by radiomike** [ochotonida/artifacts#132]
**Describe the bug**
If you hold the umbrella in either hand and sleep in a bed, the world shakes. The player model appears stationary

**To Reproduce**
1. Hold umbrella in hand or offhand
2. wait for night or `time set night`
3. go to bed
4. observe world shaking

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: Artifacts-1.16.5-2.10.4.jar
 - Forge: 36.2.26
 - curios: 4.0.5.3
 - expandability: 2.0.1

Initially noticed in atm 6. Tested in world with just artifacts and it's dependencies installed.

**Comment by ochotonida** [comment]
This appears to be an issue with Minecraft rather than Artifacts, as the exact same effect can be reproduced using the Slow Falling potion effect (https://bugs.mojang.com/browse/MC-178665). It might be fixed in more recent versions of Minecraft.
