### ISSUE TITLE
[1.18.2] Forge 40.0.18 breaks mod

### ISSUE THREAD

**Issue by Baggytrousers27** [ochotonida/artifacts#135]
Artifacts (artifacts) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

Forge 40.0.18
curios-forge-1.18.2-5.0.6.3
expandability-6.0.0
artifacts-1.18.2-4.0.5

[Crashlog](https://pastebin.com/G2MuH9Cj)

**Comment by ochotonida** [comment]
Thanks for the report! I've uploaded a patch that fixes the issue.

**Comment by Baggytrousers27** [comment]
Wow you work fast. Cheers and have a lovely day/night.
