### ISSUE TITLE
Instant Crash on 1.18.2

### ISSUE THREAD

**Issue by zachsai** [ochotonida/artifacts#137]
**Describe the bug**
Instant Crash
https://gist.github.com/WelpSTudent/fcc1515c969c14a9c50f370a9a600923
**To Reproduce**
add mod, launch

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: [40.0.6]
 - Forge: [40.0.17]
 - [100 other mods]

**Comment by ochotonida** [comment]
You are missing ExpandAbility, which is a required dependency. Additionally, the version of Artifacts you're using requires Forge 40.0.18 or higher.
