### ISSUE TITLE
Body Items Rendered Weirdly with Epic Fight Mod Player Model

### ISSUE THREAD

**Issue by pixlxip** [ochotonida/artifacts#140]
**Describe the bug**
The handheld items (and maybe more) are rendered in the wrong place with Epic Fight Mod installed.

**To Reproduce**
![2022-04-07_20 35 37](https://user-images.githubusercontent.com/99521063/162352601-5b9cf59f-22bc-4f12-a5e2-3d0623ed2be7.png)

1. Install Epic Fight Mod and Artifacts
2. Equip Power glove in left hand and put Shield in offhand
3. Go into F5 front
![Uploading 2022-04-07_20.35.45.png…]()

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: 2.1.0.5
 - Forge: 36.2.20
 - Epic Fight Mod 16.5.13

**Comment by ochotonida** [comment]
I'm not sure if there's an easy way to fix this. Epic Fight Mod replaces the player model with a different model, whereas the models in this mod are specifically made to match the vanilla model. Epic Fight Mod adds some compatibility for 3d armor models, but I'll have to look into whether this can be applied to my models as well.

**Comment by pixlxip** [comment]
> I'm not sure if there's an easy way to fix this. Epic Fight Mod replaces the player model with a different model, whereas the models in this mod are specifically made to match the vanilla model. Epic Fight Mod adds some compatibility for 3d armor models, but I'll have to look into whether this can be applied to my models as well.

ok thanks. do you think a 3rd party port would be possible for rendering it corrrectly?

**Comment by ochotonida** [comment]
While it's something I considered in the past, the amount of work it would take to make Artifacts compatible with Epic Fight doesn't really seem worth it.
