### ISSUE TITLE
Allow Campsite Y Level to be Configurable

### ISSUE THREAD

**Issue by Darkosto** [ochotonida/artifacts#143]
Hello!

I've just started using the artifacts mod in a new pack and the campsites all seem to be spawn below Y=0. My world generation is Y=-64 up to Y=688. Could we have the ability to change the Y levels that a campsite will spawn at to account for different world types? 

Thank you!
Darkosto

MC: 1.18.2 
Artifacts: 4.0.7
Forge: 40.1.0

**Comment by ochotonida** [comment]
I've uploaded an update to CurseForge that re-implements these config options. (I temporarily removed these while porting to 1.17/1.18 due to changes mojang made to world gen, and I never got around to re-implementing them until now)
