### ISSUE TITLE
Helium Flamingo HUD overlapped by modded UI

### ISSUE THREAD

**Issue by Krampus69** [ochotonida/artifacts#147]
**Describe the bug**
Helium flamingo bar is behind other mods UI (Watersource bar here)

**To Reproduce**
1. Download WaterSource 1.16.5
2. Use flamingo item and start to fly

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: Artifacts-1.16.5-2.10.5
 - Forge: 36.2.34
 - [other relevant mods...] WaterSource-1.1.40-release-1.16.5
 
You can DL ElenaiDodge2-1.16.X-1.1.0 also if you want to check with the second blue bar too like on the picture

(Love your mod btw, you're doing an excellent job thank you for your work)

![image](https://user-images.githubusercontent.com/81943963/168398332-c5c0baa2-c86c-4a69-997e-e8ff66b0f45e.png)

**Comment by ochotonida** [comment]
Thanks for the report. This seems to be an issue with WaterSource, not Artifacts. Forge adds a variable that is used to communicate to other mods how high these bars should be rendered. WaterSource does not use this, instead relying on hardcoded values that change depending on whether some mods, including ElenaiDodge2, but not Artifacts, are present.
