### ISSUE TITLE
Game crashes everytime i right-click an item

### ISSUE THREAD

**Issue by 0DarkShock0** [ochotonida/artifacts#148]
Every time i am trying to play, i equip an item (for example the night vision googles) and when i unequip it or right-click it my game crashes

**Steps to reproduce the behavior:**
1. Go to 'Inventory'
2. Click on 'any wearable item from the mod (right-click)/unequip it'
3. Game crashes 

**Game Environment**

 - Artifacts: [[artifacts-1.18.2-4.0.7.jar]
 - Forge: [1.18.2-forge-40.1.31]
 - [any type of mod that prevents crashes doesn't work]

**Comment by ochotonida** [comment]
Could you give me a crash report please?
