### ISSUE TITLE
Enhance the Flame Pendant/Fire Gauntlet so it cannot backfire on the wearer

### ISSUE THREAD

**Issue by tanyan-tanyan** [ochotonida/artifacts#149]
Hi! The Flame Pendant and Fire Gauntlet effectively set an attacker or a mob on fire. When the attacking entity hits the wearer back, the wearer is set on fire too. Is it possible to enhance these artifacts in the least invasive way possible? I thought about things like developing a modded fire which cannot be transferred or applying temporary fire resistance but both of these are not very elegant solutions. Perhaps there is a way to code immunity to fire from recently ignited mobs, while still making it possible to be set on fire from other sources like fire blocks, lava etc?

**Comment by Aizistral** [comment]
I would make them simply extinguish player at all times, granted the nature of their abilities. Just saying.

**Comment by ochotonida** [comment]
Fixed in version 1.19.3-6.0.0. The Flame Pendant will now temporarily give the player fire resistance after lighting an attacker on fire. I decided not to add this for the Fire Gauntlet since its effect is pretty much identical to Fire Aspect enchantment, which also doens't do this.
