### ISSUE TITLE
 Creeper overhaul compatibility

### ISSUE THREAD

**Issue by ConqAra** [ochotonida/artifacts#152]
Creeper overhaul creepers from 1.18.2 don't get affected by the kitty sleepers, only the vanilla creeper. perhaps this can be changed so it affects all of creeper overhaul's creepers?

**Comment by florensie** [comment]
Thanks for opening your issue here.
https://github.com/florensie/artifacts-fabric/issues/68

**Comment by florensie** [comment]
Link to mod page: https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul

**Comment by ochotonida** [comment]
Fixed in version 1.18.2-4.2.0
