### ISSUE TITLE
[1.18.2/1.19] myloot mimic compat

### ISSUE THREAD

**Issue by ConqAra** [ochotonida/artifacts#153]
Artifact's mimics will just show as normal chests when using myloot, which is obvious that their mimics. Is there a way to add compat for myloot when observing mimic chests? [I also posted this issue on the myloot github](https://github.com/spoorn/myLoot/issues/21).

**Comment by florensie** [comment]
We already have support for lootr, shouldn't be hard to do the same for myloot.

**Comment by ochotonida** [comment]
MyLoot seems to be a Fabric-only mod, so the artifacts fabric issue tracker would have been a better place for this. @florensie Can you take a look at this?

**Comment by florensie** [comment]
will look into it
