### ISSUE TITLE
Artifacts button doesn't work on my Server

### ISSUE THREAD

**Issue by 77Delta** [ochotonida/artifacts#154]
**Describe the bug**
I have a 1.16.5 Mohist Server and when i click on the Artifacts button to open the Artifacts inventory it doesn't work but when i try it on a singleplayer world it works

**To Reproduce**
1. Go to a Mohist Server with the same mods and plugins.
2. Go to the inventory.
3. Click on the Artifacts button

![2022-07-21 15-45-12 (online-video-cutter com)](https://user-images.githubusercontent.com/109739968/180229783-08295746-494e-4f5a-8d59-88b246fae3df.gif)

**Game Environment**
 - Artifacts: 1.16.5-2.10.5
 - Forge: 1.16.5-36.2.35
 - Mohist: 1.16.5-1055

 - Plugins: Citizens, Essentials, PixelHider, Plugin Hide, SkinsRestorer, Animated TabList, Vault, WorldEdit, WorldGuard.

 - Mods: Abnormals Core, Alex's Mobs, Ambient Sounds, AppleSkin, Aquaculture 2, Architectury, Artifacts, Atum 2, Better Advancements, Biomes O' Plenty, Bookshelf, Bountiful, Charging Gadgets, Chisels & bits, Citadel, Cloth Config v4 API, Collective, Crafting Tweaks, CreativeCore, Croptopia, Curios API, DarkPaintings, Doggy Talents 2, Dragon Mounts: Legacy, Dungeons Mod, Emojiful, Emotecraft, End Remastered, Evolved RPG, Exotic Critters, ExpandAbility, Extra Bows, FPS Reducer, GeckoLib, Goblin Traders, HT's TreeChop, Inventory HUD+, Inventory Pets, Journeymap, JRFTL, Just Enough Items, Mining Gadgets, Mining Helmet, Mining World, More Villagers, Mowzie's Mobs MrCrayfish's Furniture Mod, MrCrayfish's Gun Mod, Obfuscate, Pirates and Looters Reborn, PlayerRevive, SecurityCraft, Selene, Simple Planes, Simple Voice Chat, Slimier Slimes, Sound Filters, Spartan Shields, Spartan Weaponry, Stack Refill, Stroage Drawers, Structure Gel API, Structure Toolkit, Supplementaries, The Conjurer, The Farlanders, The Gaia Dimension, The Outer End, The Twilight Forest, The Undergarden, TrashSlot, Traveller's Boots, U Team Core, Useful Backpacks, Waila, Waystones, When Dungeons Arise, Whisperwoods, YUNG's API, YUNG's Better Caves, YUNG's Better Strongholds.

**Comment by florensie** [comment]
We're can't provide support for issues with mohist. Either way, this button is not added by Artifacts but Curios.
