### ISSUE TITLE
Green/grayscale overlay and overexposure for Night Vision Goggles

### ISSUE THREAD

**Issue by ChloeDawn** [ochotonida/artifacts#156]
It would be nice if there were an option to enable a green or grayscale overlay to the screen (akin to realistic night vision) when wearing night vision goggles, and to have them overexpose when in brighter areas of the world such as the surface during the day, or torch light underground, to make wearing them in bright conditions detrimental to the player. I personally find the goggles to be a little too powerful as an item and something like this would help to balance them. Overexposure could be achieved by adjusting the gamma of the game, I think.

**Comment by ochotonida** [comment]
The latest version of Artifacts reduces the strength of the night vision goggles a bit. I don't think I'm going to add a green/gray overlay or overexposure though. I personally don't really like the idea of making everything green/gray, and overexposure wouldn't really help making the goggles less powerful when you can just take them of.
