### ISSUE TITLE
Artifacts (artifacts) encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by KyrDerz** [ochotonida/artifacts#157]
A crash. No idea why or how. But I added crash reports
[crash-2022-08-18_23.06.47-fml.txt](https://github.com/ochotonida/artifacts/files/9377981/crash-2022-08-18_23.06.47-fml.txt)
[crash-2022-08-18_22.57.35-fml.txt](https://github.com/ochotonida/artifacts/files/9377982/crash-2022-08-18_22.57.35-fml.txt)
.

**Comment by ochotonida** [comment]
Should be fixed in version 1.18.2-4.2.0
