### ISSUE TITLE
[1.18.2 Forge Artifacts BUG] helium_flamingo bug lagg in flight

### ISSUE THREAD

**Issue by MrJorman** [ochotonida/artifacts#162]
**Describe the bug**

**To Reproduce**
**Move to hell, put on a flamingo and fly with CTRL and fly up to the ceilings and walls. Now just die with the command /kill or from the monster. Next, go to hell again and dress up flamingos, now fly to the ceiling or to the walls (you will receive damage from landing as well as lag at the walls or ceilings of blocks)**

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: [artifacts-1.18.2-4.1.0.jar](https://www.curseforge.com/minecraft/mc-mods/artifacts/files/3771085)
 - Forge: 1.18.2 - 40.1.76 and 1.18.2 - 40.1.0 testing
 - CuriousAPI and ExpandAbility

**Comment by ochotonida** [comment]
This seems to be a hitbox desync issue with ExpandAbility, @florensie can you take a look at this? You can reproduce it by teleporting to another dimension and flying into the underside of a block.

**Comment by GitJhopa** [comment]
Bug no fixing!!

**Comment by florensie** [comment]
Likely related to #205

**Comment by ochotonida** [comment]
Seems like I unintentionally fixed this issue by fixing #205 in version 4.2.2/6.1.1

**Comment by GitJhopa** [comment]
Where can I download the build with the fix?

**Comment by GitJhopa** [comment]
for 1.19.2 forge

**Comment by ochotonida** [comment]
I didn't fix it for 1.19.2 yet, I'll try to get a patch out later today

**Comment by GitJhopa** [comment]
thank.

**Comment by ochotonida** [comment]
Version 1.19.2-5.0.3 should fix the issue
