### ISSUE TITLE
Expandability Dependency Not Recognized  

### ISSUE THREAD

**Issue by HauntedToast** [ochotonida/artifacts#174]
**Describe the bug**
When I launch MC Forge 40.1.80 with Artifacts 1.18.2 - 4.2.0 and expandability, I keep getting a dependency error that says that expandability 6.0.0 or above needs to be installed. The only issue is that expandability 6.0.0 is installed and it is not recognizing it.

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: 1.18.2-4.2.0
 - Forge: 40.1.80
 - Expandability: 6.0.0

Crash Report: https://pastebin.com/Qa0v6aFF

Keep in mind I have other dependencies I still need to install for other mods, but this one does not make any sense.

**Comment by florensie** [comment]
Did you install the right version of expandability for your mod loader? There are separate versions for Forge and Fabric.

**Comment by HauntedToast** [comment]
Yes. I even downloaded the forge one again and placed it in the folder and same issue

**Comment by florensie** [comment]
Can you try resolving the other dependency issues first? This might just be some Forge weirdness. You could also try without any other mods.

**Comment by HauntedToast** [comment]
I figured it out. Thank You

**Comment by ochotonida** [comment]
Do you mind sharing what solved the issue in case someone else is having a similar problem? Just saying 'I figured it out' isn't very helpful.

**Comment by HauntedToast** [comment]
Yeah I downloaded the forge file for a third time and installed it. It seems like the files kept getting corrupted
