### ISSUE TITLE
artifacts won't load

### ISSUE THREAD

**Issue by Hiccupwarrior89** [ochotonida/artifacts#175]
artifacts is crashing upon opening the game

open minecraft with artifacts installed (it is installed with around 30 other mods but has never crashed with them before)

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: 4.2.0
 - Forge: 40.1.80
 - Curios: 5.0.7.1

**Comment by ochotonida** [comment]
When your game is crashing we can't really help much without a log/crash report.
