### ISSUE TITLE
[1.19.2] Plastic Dringking Hat and Novelty Drinking Hat share same config

### ISSUE THREAD

**Issue by RedBeast1959** [ochotonida/artifacts#178]
**Describe the bug**
I changed Plastic Drinking Hat and Novelty Drinking Hat config, so that PDH can reduce more eating duration and NDH reduce more drinking duration. However, it seems two item share same config. I just only changed PDH config, but NDH was also applied by PDH config.

**To Reproduce**
1. Change Plastic Drinking Hat eating and drinking duration multiplier
2. Equip Novelty Drinking Hat
3. Drink or eat something
4. Now watch PDH config change applied to NDH 

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: artifacts-1.19.2-5.0.0.jar
 - Forge: 43.1.32
 - Oher relevant mods: Artifacts Only

**Comment by ochotonida** [comment]
Thanks for the report, the issue should be fixed in version 5.0.1
