### ISSUE TITLE
Registry Object not present: artifacts:novelty_drinking_hat

### ISSUE THREAD

**Issue by LaAbuelawe** [ochotonida/artifacts#182]
When I want to open minecraft forge 1.19.2, with the mod artifac, It apear a message that says: Artifacts (artifacts) encountered an error during the common_setup event phase
		java.lang.NullPointerException: Registry Object not present: artifacts:novelty_drinking_hat

I have tried to download from differents pages but it says the same.

**Comment by ochotonida** [comment]
Please fill out the issue template next time.
What version of Forge and Artifacts are you using? Are you using any other mods?
I'll also need a log/crash report, otherwise I probably won't be able to help.

**Comment by ochotonida** [comment]
I'm closing this issue as I don't have the required information to reproduce it. If you're still having this problem, feel free to open a new issue with the requested information.
