### ISSUE TITLE
Change the pendant models so there is no longer render flickering with the outer skin layer

### ISSUE THREAD

**Issue by Gronglegrowth** [ochotonida/artifacts#183]
Currently, some artifacts (shock, flame, and thorn pendant were tested) clip with the outer skin layer, causing flickering; [example](https://media.discordapp.net/attachments/801591103375015957/1039696758466416650/Screenshot_20221108_192053.png).

Could these models be altered slightly so they no longer do this?

**Comment by ochotonida** [comment]
Fixed in version 1.19.2-5.0.2
