### ISSUE TITLE
Artifacts and CarryOn - 1.19.2

### ISSUE THREAD

**Issue by mpcarlos87** [ochotonida/artifacts#187]
**Describe the bug**
Having both Artifacts and CarryOn mods installed on Minecraft 1.19.2 and Forge 43.2.3, I get a crash at startup.

**To Reproduce**
1. Run CurseForge App
2. Create a profile for Minecraft 1.19.2 with Forge 43.2.3
3. Install Artifacts (artifacts-1.19.2-5.0.1.jar) and CarryOn (carryon-forge-1.19.2-2.0.3.4.jar) mods
4. Click on "Play" in CurseForge app
5. Click on "Play" in Minecraft launcher 
6. Game crashes and I get this error
![20230122-Crash](https://user-images.githubusercontent.com/4833414/213938385-60a03deb-6b5d-48bb-b94d-0eae54963547.PNG)

**Game Environment**
 - Artifacts: 1.19.2
 - Forge: 43.2.3
 - CarryOn: [carryon-forge-1.19.2-2.0.3.4](https://www.curseforge.com/minecraft/mc-mods/carry-on/files/4352489)

**Edit**
Previous version of CarryOn works fine (carryon-forge-1.19.2-2.0.2.3.jar)
 
 Added a comment in CarryOn issue: https://github.com/Tschipp/CarryOn/issues/452

**Comment by riseon** [comment]
I think this might actually be a problem with the ExpandAbility library.  I get this error with the library but not artifacts active

https://github.com/florensie/ExpandAbility/issues/2

**Comment by ochotonida** [comment]
This issue was fixed in CarryOn version [2.0.5.10](https://www.curseforge.com/minecraft/mc-mods/carry-on/files/4375891).
