### ISSUE TITLE
[1.19.3] Crash on/before world creation, possible interaction with Minecolonies

### ISSUE THREAD

**Issue by EvergreenSystems** [ochotonida/artifacts#191]
**Describe the bug**
Whenever an existing world is loaded, minecraft throws the "datapacks in this world are broken, load in safe mode" screen, and when "create a new world" is clicked the game crashes.

**To Reproduce**
1. Attempt to create a new world, or load an existing world (only creation causes this crash afaik).

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: [1.19.3-6.0.0]
 - Cloth Config v9 API [9.0.94]
 - Forge: [44.1.17]
 - Minecolonies [1.19.3-1.0.1252-ALPHA]

Crash Report: https://gist.github.com/Shedao-Shai/97da1fb0ebec5542a07c49647c1f87d4

**Comment by ochotonida** [comment]
Fixed in version 1.19.3-6.0.1
