### ISSUE TITLE
Release on Modrinth.com

### ISSUE THREAD

**Issue by CodeF53** [ochotonida/artifacts#192]
Modrinth is an alternative to Curseforge which is way better in a few key aspects:
  -  Proper filtering
     - on Curseforge you can search for 1.17 mods, or fabric mods, not 1.17 fabric mods
     - client/server mod filters
  -  Fast searches
     -  It takes nanoseconds for the search results to update to what you have typed, as opposed to the 3-5 seconds Curseforge does
  - Easier API integration
     - Well documented, easy to use api
     - You can ask for support from actual humans

This is easily the best Trinkets mod and yet I dread installing it because I have to tolerate Curseforge to get it.

**Comment by florensie** [comment]
Artifacts has been available on modrinth for a while now.
https://modrinth.com/mod/artifacts/versions
