### ISSUE TITLE
Creeper Overhaul Issue

### ISSUE THREAD

**Issue by ereese99** [ochotonida/artifacts#193]
The cat slippers don't repel creepers from Creeper Overhaul.

**Comment by florensie** [comment]
What version of the mod are you on, this was implemented a while ago.

**Comment by ereese99** [comment]
artifacts-7.1.1+fabric.jar
creeperoverhaul-2.0.8-fabric.jar

**Comment by ochotonida** [comment]
The forge version already has this, but it seems like the latest Fabric version is still running behind on this. This issue tracker is only for general suggestions or issues with the Forge version, so let's move this to the issue tracker for the fabric version instead.
