### ISSUE TITLE
equipping hand item crash

### ISSUE THREAD

**Issue by kaairu** [ochotonida/artifacts#198]
**Describe the bug**
i equipped that hook that gives u more xp when killing mobs and my game crashed

**To Reproduce**
equip the hook thing

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: artifacts-1.19.2-5.0.2.jar
 - Forge: 43.2.6
 - elytra slot, dungeons gear, curious lanterns, crafting on a stick, backpacked, goety

[crash-2023-03-25_03.16.49-client.txt](https://github.com/ochotonida/artifacts/files/11068616/crash-2023-03-25_03.16.49-client.txt)
I also have the log.txt however that shit is 50 MB for some reason due to a mod that has a lot of weird debug stuff in it.

**Comment by ochotonida** [comment]
This crash is caused by Goety, not Artifacts.
