### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by oleg12054** [ochotonida/artifacts#199]
I would like to add several items with similar functions to this mod for my own purposes, please tell me what needs to be added in order to get a full-fledged artifact? what parts of the code are affected?

the first item had the same properties as "Helium Flamingo", but twice (2 times) longer duration, and if possible, accelerated swimming through the air by 50%, removed fall damage (for example, with an effect)
the second item I would like to add two (2) times more HP to the player when wearing, while both artifacts are acceptable (both original and enhanced = +30 hp, sort of)

> PS: I tried to add an item, I got only a texture and the item itself, I couldn't add unique properties to it...

**Comment by ochotonida** [comment]
There isn't anything special about the items Artifacts adds compared to items from other mods, maybe apart from that they're curios. While there are some design decisions most artifacts follow, such as having a simple/easy to understand effect and a unique looking model when equipped, the actual code you need to implement your items is entirely dependent on the effect you want your items to have, and that's not something I can help with.

I'd suggest asking somewhere where there's other people that can help with general modding questions, like the Forge or MMD discord. This issue tracker isn't the right place to ask for modding help.
