### ISSUE TITLE
Setting the rarity of particular artifacts.

### ISSUE THREAD

**Issue by Lord-Volkner** [ochotonida/artifacts#200]
Where can this be changed? I've found 30 artifacts. Now I have 20 pairs of kitty slippers and 10 pairs of the bunny hoppers and zero of everything else. Every game I've played has been the same. I found the config files, but it doesn't seem possible to adjust the drop chance of individual artifacts. It would be nice if it was far more random.

Thanks
V

**Comment by ochotonida** [comment]
The reason that there's no config options for this is that it would be too much work to implement and maintain, when the same result and more can already be achieved by overriding Artifact's loot tables using a data pack.
Keep in mind that most artifacts only have a few places where they can be found, so which items you find depends a lot on where you're looking. The images tab on CurseForge lists where each artifact can be found if you're curious

**Comment by Lord-Volkner** [comment]
> The images tab on CurseForge lists where each artifact can be found if you're curious

Thanks
