### ISSUE TITLE
Capabilities are not saved in dimension changes

### ISSUE THREAD

**Issue by lilchicky** [ochotonida/artifacts#205]
The sinking charm necklace does not save the "shouldSink" capability between dimensions. Changing dimensions renders the item non-functioning.

Equip the necklace
Jump in water (it works)
Travel to Nether, then back again, and jump in the same water
You no longer sink, but swim normally

 - Artifacts: 4.2.1
 - Forge: 40.2.0
 - Chicky's Fester Forest, Undergarden, etc. all behave similarly
 - Minecraft: 1.18.2

**Comment by ochotonida** [comment]
Fixed in version 4.2.2/6.1.1
