### ISSUE TITLE
Thorn Pendant causing server crash (Ticking Entity)

### ISSUE THREAD

**Issue by 0xhayleydev** [ochotonida/artifacts#206]
**Describe the bug**
Crash appears when players are wearing the Thorn Pendant.
Since telling players to take this off, the server hasn't crashed meaning I believe its to do with this item in particular.

**To Reproduce**
1. Wear Thorn Pendant
2. Have skeleton/wither skeleton attack you
3. Server crashes with "Ticking Entity" error.

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: 1.19.2-5.0.2
 - Forge: 42.2.11
 - Part of ATM 8 pack

**Crash Reports**
https://pastebin.com/H5cmdm2r

https://pastebin.com/0EHvV95z

https://pastebin.com/u8HRLuzr

https://pastebin.com/mKkHDkbC

https://pastebin.com/Cu81EmEt

https://pastebin.com/PTUAHewe

**Comment by ochotonida** [comment]
Sorry for the late response, I haven't been able to reproduce this thus far (even though there's be plenty of similar reports on the ATM 8 issue tracker). Considering that the crash can be reproduced with the vanilla Thorns enchantment https://github.com/AllTheMods/ATM-8/issues/706#issuecomment-1537058832, I don't think this should be considered an issue with Artifacts.

Unfortunately the crash logs aren't very informative for determining which mod is to blame. The only thing of note is that there's a mixin redirect involved, added by one of the following mods: [kubejs, supplementaries, botania, immersiveengineering, byg, ad_astra, observable, create]. I doubt that this is what's actually causing the problem though.
