### ISSUE TITLE
when opening starter chest game crashes

### ISSUE THREAD

**Issue by krjencik** [ochotonida/artifacts#207]
**Describe the bug**

**To Reproduce**

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: [version] artifacts-1.20.1-7.0.0.jar
 - Forge: [version] 47.1.0
 - [other relevant mods...]

latest log:

https://gist.github.com/krjencik/62e23a64470c461eea856973d119d80f

**Comment by Ramsch1** [comment]
Is there any version for 1.20.1 without this bug?

**Comment by Ramsch1** [comment]
Describe the bug
Game Crashes when opening vanilla chests

Error Message:
"The game crashed whilst exception in server tick loop
Error: java.lang.StackOverflowError: Exception in server tick loop"

Artifacts: [version] artifacts-1.20.1-7.0.0.jar
Forge:  47.1.0
[other relevant mods...]

**Comment by ochotonida** [comment]
Fixed in version 7.0.1. Please fill in the issue template properly next time, it makes it a lot easier to reproduce and fix the issue.
