### ISSUE TITLE
[1.20.1] crash killing a drowned zombie that mentions 'mixins.artifacts.json:item.aquadashers.EntityMixin'

### ISSUE THREAD

**Issue by Lothrazar** [ochotonida/artifacts#211]
**Describe the bug**
I was playing with forge 47.1.3 and Artifacts 1.20.1-7.0.2 .. killed a drowned zombie with a wooden sword, and the game crashed with this log .Artifactory might not be root cause, its hard to read logs with mixins .
the drowned was swimming and doing some bubbley thing at the time of the fight, player was on dry land if that matters. it may have been just taking damage and not dying. uninstalled artifacts 7.0.2 and rejoined the world and i was able to kill them without a crash.

**To Reproduce**
1. install versions mentioned above
2. kill a drowned zombie
3. 

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: [1.20.1-7.0.2 ]
 - Forge: [47.1.3]
 - there could be other mixins involved, it mentions expandability.mixins.json: and :maxhealthfix.common.mixins.json
 LOG:
https://pastebin.com/SQ4Pw8jp
 
First snippet of log is 
 ```java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_5647_()" because "p_20355_" is null
	at net.minecraft.world.entity.Entity.m_7307_(Entity.java:2232) ~[client-1.20.1-20230612.114412-srg.jar%23328!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:```

**Comment by ochotonida** [comment]
Sorry for the late reply. As far as I'm aware this can't be caused by Artifacts, the issue seems to be something setting lastHurtByMob to null at the wrong time. The only time Artifacts modifies lastHurtByMob is after a creeper is hit by a player wearing Kitty Slippers, drowned and other mobs are unaffected.
