### ISSUE TITLE
Bug with character and artifacts

### ISSUE THREAD

**Issue by FutMC23** [ochotonida/artifacts#213]
**Describe the bug**
The objects do not appear when I place them on my character.

 - Artifacts: [1.2.3]
 - Forge: [1.12.2]

![Bug](https://github.com/ochotonida/artifacts/assets/141523641/caa8c406-1b5a-47fd-8a26-7f3dfc985772)

**Comment by ochotonida** [comment]
It looks like you're using a mod that changes how the player model is rendered, which is likely what is causing this issue.
Artifacts is no longer being actively maintained for Minecraft 1.12, so you'll have to either remove the mod that is causing this or play without cosmetics.
