### ISSUE TITLE
[1.20.1] artifacts crash on launch

### ISSUE THREAD

**Issue by temyy** [ochotonida/artifacts#215]
artifacts crashes on both server and client when trying to launch minecraft. artifacts version 9.0.0, minecraft 1.20.1 on quilt loader 0.19.2

[latest.log](https://github.com/ochotonida/artifacts/files/12292964/latest.log)
[crash-2023-08-08_18.04.14-client.txt](https://github.com/ochotonida/artifacts/files/12292968/crash-2023-08-08_18.04.14-client.txt)

**Comment by ochotonida** [comment]
Seems like a compatibility issue between Porting Lib and some other mod you're using. I don't think there's much I can do about this on my end unfortunately

**Comment by temyy** [comment]
gotcha, i can try and narrow down which mod it happens with

**Comment by temyy** [comment]
figured it out, disabling the Lets Do API (https://www.curseforge.com/minecraft/mc-mods/do-api) and all of its dependants got rid of the error. i can bring this up with the developer of the Lets Do series

**Comment by temyy** [comment]
the api is incompatible with the porting lib, developer said it should be fixed soon though

**Comment by ochotonida** [comment]
I managed to fix it on my end as well, I didn't need to rewrite a whole lot to remove the module causing the problem in the end. I'll release a patch asap
