### ISSUE TITLE
[Bug] Crash on Startup in Quilt

### ISSUE THREAD

**Issue by Dragonfly-Totem** [ochotonida/artifacts#216]
[crash-2023-08-13_10.07.12-client.txt](https://github.com/ochotonida/artifacts/files/12329680/crash-2023-08-13_10.07.12-client.txt)

**Game Environment**
Minecraft 1.20.1
Quilt Loader 0.19.2
[QFAPI 7.1.1, QSL 6.1.1 // FAPI 0.81.1](https://modrinth.com/mod/qsl/version/7.1.1+0.86.1-1.20.1)
Architectury 9.1.12
Trinkets 3.7.1
Cloth Config 11.1.106 (see below)

Fairly straightforward as experienced -- In the Quilt loader, the game crashes when attempting to start with Artifacts.  Launcher displays error: The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'artifacts'!

What's interesting to note is that this error populates when I isolate mods down to _just_ Artifacts and the necessary libraries to _run_.  When I load my _full_ modlist, however, Artifacts seems to load and function just fine -- Which seemed _really_ effing odd.  After doing some toggle-testing, it seems like having Cloth Config added to the list is what's allowing things to run.  What, exactly, is allowing that?  I dunno.

**Comment by Dragonfly-Totem** [comment]
Closing bug out myself, because re-reviewing the frigging Artifacts dependencies, it _explicitly says_ Cloth Config required.

I am illiterate, please enjoy the laugh track. :)

**Comment by ochotonida** [comment]
Seems like I forgot to add Cloth Config as a dependency in the mod.json, I'll fix that right now so it actually tells you what's wrong rather than just crash on startup. Thanks for the report!
