### ISSUE TITLE
[Bug] Partial Functionality Loss of HWG When Using Artifacts

### ISSUE THREAD

**Issue by Dragonfly-Totem** [ochotonida/artifacts#217]
**Game Environment**
Minecraft 1.20.1
Quilt Loader 0.19.2
[QFAPI 7.1.1, QSL 6.1.1 // FAPI 0.81.1](https://modrinth.com/mod/qsl/version/7.1.1+0.86.1-1.20.1)
Architectury 9.1.12
Trinkets 3.7.1
Cloth Config 11.1.106
Happiness (is a) Warm Gun 1.4.14
AzureLib 1.0.20
SmartBrainLib 1.11.1

_Unlike the other bug report I just submitted and closed (#216), I don't **think** I'm missing anything obvious._

I'm not quite sure what might be causing the conflict, and whether it's an issue on HWG or Artifacts' end.  Most of the guns in HWG function as expected -- However, some of them.. Sort of do?  When firing (right-click), some guns play a sort of half-animation, lowering the gun and raising it, and only _very occasionally_ doing the expected firing of the weapon.

It appears to affect most of the weapons in the mod.  It seems like for any of them that don't have an immediate-and-constant fire (like an AK-47), it's sort of.. Trying to do something _else,_ and that's interfering with the actual processing of HWG's code.

It seems to be an issue isolated to something within Artifacts' code, specifically; If I remove Artifacts but keep all the other mods listed above, HWG begins functioning normally and as expected.  Artifacts appears to be completely unaffected by the presence of HWG.

**Comment by ochotonida** [comment]
Thanks for the report! I think I know what might be causing this, I'll try to get a patch out soon

**Comment by ochotonida** [comment]
Should be fixed in version 9.0.3
