### ISSUE TITLE
[1.19.2 Forge] Bug - kitty_slippers

### ISSUE THREAD

**Issue by GitJhopa** [ochotonida/artifacts#222]
The artifacts:kitty_slippers artifact does not protect against creepers from mods, for example from the CavernsChasms mod from the Abnormals mod, if it's not difficult for you to add a creeper to the mod code - caverns_and_chasms:deeper

**Comment by ochotonida** [comment]
Adding the creeper to the `artifacts:creepers` entity tag should work if they're implemented similar to vanilla creepers. This can be accomplished with a data pack.

I don't have any intention to add support for Caverns and Chasms to Artifacts at this time. The mod is closed source and locked behind a paywall, making it impossible for me to test if it actually works.
