### ISSUE TITLE
[1.19.2 Forge] Alex's Mobs Ghostly Pickaxe + Artifacts mod = dupe all resources

### ISSUE THREAD

**Issue by GitJhopa** [ochotonida/artifacts#223]
see video: https://youtu.be/huhsx7BDuco

**Comment by GitJhopa** [comment]
Ghost pickaxe in Alex's Mobs mod holds items if your inventory is full. But when I put on the claws from your mod - and break the blocks - they fall to the ground and are stored in the pickaxe, thereby duping occurs.

**Comment by GitJhopa** [comment]
https://github.com/AlexModGuy/AlexsMobs/issues/1630

**Comment by ochotonida** [comment]
Fixed in version 5.0.4.
Due to how the Ghostly Pickaxe is implemented, the digging claws will no longer work when using it. That's not something that can be fixed on Artifacts' side.
