### ISSUE TITLE
Issue [1.20.1]

### ISSUE THREAD

**Issue by GlauberBlox** [ochotonida/artifacts#224]
Well, i am here to describe the stupid issue i am having right there
I really dont know why no one that downloaded the mod had the balls to go here and describe the issue

Basically, i put the mod in mods folder, and when i open minecraft it instantly crashes, does the mod require a library? something to run it? i tested curious and also the mod alone in my mod folder and the minecraft is still crashing, i dont know how to solve this bug, please help i really want this mod in my SMP.

**Comment by GlauberBlox** [comment]
Only the version 7.0.2 together with the cloth library is working for me, but i want to use the snorkel and this version does not has it

**Comment by GlauberBlox** [comment]
only the version 9.0.0 and 9.0.5 crashes my game, while version 7.0.2 works normally. (with cloth library)

**Comment by florensie** [comment]
Please share your log file.

**Comment by ochotonida** [comment]
Please make sure you have Architectury installed, it's listed as a dependency on CurseForge/Modrinth.

**Comment by GlauberBlox** [comment]
I didn't found the library mod until i clicked in relations LOL! i didn't even saw the relations button, but thanks anyways.
