### ISSUE TITLE
Add Config To Not Render Artifacts On Player

### ISSUE THREAD

**Issue by MysticWolfy** [ochotonida/artifacts#229]
My suggestion is to add a client config to make it so you can hide the artifacts that are wearable so you do not have to have all those things on your character as I personally really like to be able to see my skin and armor and things while also having the Artifacts.

**Comment by ochotonida** [comment]
It's already possible to hide artifacts. If you're using Forge there's a button next to the slot you put it in, and for Fabric/Quilt you just right-click the item in your inventory. I'm aware that it's not very clear that this exists in the Fabric version right now, I plan on into improving this a bit in the future.
