### ISSUE TITLE
Artifacts negates modifiers of mob experience drop from some mods (Auto Leveling mod)

### ISSUE THREAD

**Issue by stsnc** [ochotonida/artifacts#231]
**Describe the bug**
This bug may appear with some mods that modify the amount of experience dropped from mobs. If Artifacts is installed, the default amount of experience is dropped in these mods instead of their modified amount. This affects, at least, the Auto Leveling mod (In it, mobs should drop more experience the higher their level, but this does not happen only if Artifacts is installed). I guess that may affect other mods as well.

I note that this bug does NOT affect mob experience drop modifiers from Iron's Spells 'n Spellbooks mod and Passive Skill Tree mod. Between themselves, with Artifacts and with Auto Leveling, these mods interact correctly.
I guess the reason is that Iron's Spells 'n Spellbooks and Passive Skill Tree use getDroppedExperience() in the setDroppedExperience() method instead of getOriginalExperience() and/or are loaded later than Artifacts.

**To Reproduce**
1. Install Auto Leveling along with Artifacts.
2. Make sure that bonus expirience per level is set to higher then 0 in the autoleveling-common config (it should already be set to 10% by default)
3. Spawn a mob with a high level and kill it. For example, a zombie with level 10. To do this, either fly away to a sufficient distance from the spawn, or enter /autoleveling level add 9 and spawn the mob on the spawn.
4. Check the amount of experience
5. Do the same, but remove Artifacts from your modpack. With Artifacts installed, it drops less experience (vanilla amount)

**Game Environment**
 - Artifacts: 9.1.0
 - Forge: 47.2.0
 - Auto Leveling: 1.18
 - Cloth Config API: 11.1.106
 - Curios API: 5.3.5+1.20.1

**Comment by ochotonida** [comment]
Thanks for the report! Should be fixed in version 9.2.0.
