### ISSUE TITLE
Crash when killing cow or mooshroom

### ISSUE THREAD

**Issue by TiGReX423** [ochotonida/artifacts#238]
**Describe the bug**
   After killing cow or mooshroom cow, loop starts to give loot from poor animal, but after 1000 tries it stops and crashes. And then another crash telling that tick was too big. 
   BUT it wasnt from beginning of world. I play with gf and we survived few days (10hours of gameplay maybe?). Today she was exploring world further and she was killing cows for materials.. and crash happened. I didn't kill cows before, so I assumed that I can kill cows, till that chance when I get special item, but no. I killed cow - got crash anyway. Is it global chance?
   Anyway here is everything I figured out. By the way, after deleting only Artifacts problem solved. It is not an option.
   My gf tried to go single player world. And after 1 cow she got crash.

**To Reproduce**
-Start server.
-Summon cows or mooshrooms (red cow).
-Kill it. Kill them more.
-Get 2 crashes:
1)"Description: Exception in server tick loop"
https://drive.google.com/file/d/1x9Uwk84Z6ccnWlLLsFp8IWDiltsDf2jJ/view?usp=sharing
2)(Not related to actual crash cause) "Description: Watching Server"
https://drive.google.com/file/d/1x9Uwk84Z6ccnWlLLsFp8IWDiltsDf2jJ/view?usp=sharing

**Game Environment**
Can not really tell what is caused to do loop in loot from cow. But I did find that there was 0.002 to get "everlastingBeefChance" from cow or mooshroom. I changed it from 0.002 to 0.0 but it didnt work. 
 - Artifacts: 7.0.0
 - Forge/Fabric Api: Forge 47.2.19
 - and +210 mods

**Comment by ochotonida** [comment]
You're using an outdated version of Artifacts, this crash in particular was fixed over 6 months ago
