### ISSUE TITLE
How can I disable the cosmetic slots?

### ISSUE THREAD

**Issue by MaikiNG12** [ochotonida/artifacts#24]
I want to disable the cosmetic slots, but I don´t know how

**Comment by tanyan-tanyan** [comment]
There is a smaller box next to every cosmetic slot if I'm not mistaken, however certain boxes toggle wrong items or do not respond in any way.

**Comment by ochotonida** [comment]
Sorry for getting to this this late. While the cosmetic slots are technically added by this mod, they're actually a feature of the Curios API. I haven't tested this myself, but you should be able to disable them in the curios config, more information here under "Creating a New Slot Type": https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users.
Basically, just create an entry for each slot type that has a cosmetic slot kinda like this:
```
[[curiosSettings]]
  identifier = "<identifier>"
  hasCosmetic = false
  override = false (this property is probably not needed)
```
If you need any more help just let me know.
