### ISSUE TITLE
Is it appropritate to add memes when translating?

### ISSUE THREAD

**Issue by Snapshotlight** [ochotonida/artifacts#241]
I am wondering this when I check the zh_cn.json in which there are tons of memes that deviate from the original text. Though I want to submit another version of Chinese translation, I think it is better to ask your opinion.
btw, in my view translation should align with the original text.

**Comment by ochotonida** [comment]
Yes, in general translations should align with the English localization. Sentences don't need to be translated word for word, but adding jokes and such that aren't in the original text is going a bit too far. Feel free to submit a PR with corrections if you want
