### ISSUE TITLE
incompatible with sophisticated storage chests

### ISSUE THREAD

**Issue by myst0sis** [ochotonida/artifacts#244]
Any generated campsite uses sophisticated storage chests and there isnt anything inside when opened

 - Artifacts: 1.18.2 4.2.2
 - Forge 40.2.4
 - sophisticatedstorage 1.18.2-0.8.55.679
 
 the full modpack:
 - https://legacy.curseforge.com/minecraft/modpacks/tsmp-tortuguitassmp

**Comment by ochotonida** [comment]
Thanks for the report. I believe I already have a fix for this, but never backported it to 1.18.2. As a temporary workaround, you can set `useModdedChests` to false in the common config to fix this on your end.

**Comment by myst0sis** [comment]
okay cool ill try that. thank you!

**Comment by ochotonida** [comment]
Should be fixed in version 4.2.3/5.0.5. Campsites now use chests from the `artifacts:campsite_chests` block tag which by default only includes the vanilla chest and Quark's wooden chests. This only applies to newly generated chunks though.
