### ISSUE TITLE
Unlit campfires config option

### ISSUE THREAD

**Issue by RainbowSaber** [ochotonida/artifacts#248]
I would greatly appreciate a config option that places the underground Campsite structure with a campfire with the unlit blockstate. The campfire makes it very easy to spot the campsites, especially in large caverns and is one of the only structures in many modpacks that generates with active lightblocks in a hostile environment.

It also breaks "No hostiles around campfires" and basically disables undeground map spawning with both mods installed.

**Comment by ochotonida** [comment]
I've added a config option that does this in the latest update, I've also lowered the amount of light sources that spawn by default a bit.
