### ISSUE TITLE
JEI x Artifacts x Supplementaries   JEI cheat mode crash  ''Index Out of bounds''

### ISSUE THREAD

**Issue by ALainxD** [ochotonida/artifacts#250]
When you go into creative mode, open JEI, activate cheat menu and give yourself a Item the game crashes ONLY if also supplementaries is installed. 
If Supplementaries OR Artifacts is disabled it works fine, but both active it causes that crash.

**To Reproduce**
1. Make a new Fabric 0.15.7 MC1.20.1 instance
2. add mods: JEI, Supplementaries and Artifacts and their dependencies.
3. Start MC, make new world, creative mode, start world.
4. Open your inventory, go to the normal player inventory (not in a creative items tab), enable cheat mode in JEI and give yourself a item.
5. Minecraft crashes 
6. MC error code: ''The game crashed whilst mousereleased event handler
Error: java.lang.IndexOutOfBoundsException: Index 54 out of bounds for length 54''

**Game Environment**
Fresh install Fabric
 - Artifacts: artifacts-fabric-9.3.1.jar
 - Forge/Fabric Api: Fabric 0.15
- Other mods needed -> 
Amendments 1.20-1.1.10 [required by Supplementaries]
Architectury 9.2.14             [Required by Artifacts]
Artifacts 9.3.1
Cloth Config v11 11.1.118  [required by Artifacts]
Fabric API 0.92.0+1.20.1  
Fabric Loader 0.15.7
Just Enough Items 15.3.0.4
moonlight-1.20-2.11.4-fabric.jar [required by Supplementaries]
Supplementaries 1.20-2.8.6
Trinkets 3.7.2

btw is there a specific reason why Curseforge launcher doesn't install Architectury, Cloth Config and Trinkets when installing Artifacts?
Are the dependencies not labled correctly?

**Comment by ALainxD** [comment]
[crash-2024-03-16_20.08.21-client.txt](https://github.com/ochotonida/artifacts/files/14624985/crash-2024-03-16_20.08.21-client.txt)
Crashlog

**Comment by ALainxD** [comment]
Supplementaries issue post 
https://github.com/MehVahdJukaar/Supplementaries/issues/982

**Comment by ALainxD** [comment]
JEI Issue post
https://github.com/mezz/JustEnoughItems/issues/3460

**Comment by ochotonida** [comment]
It seems like the same issue occurs with Botania (https://github.com/VazkiiMods/Botania/issues/4365).
I honestly have no idea how Artifacts could cause something like this, so I'm more inclined to believe that this is something on either Trinkets' or JEI's side.

**Comment by ochotonida** [comment]
I managed to reproduce this issue with just Trinkets, JEI, and a data pack, so it's definitely not caused by Artifacts. You need 8 or more trinket slots to trigger the crash, which explains why it doesn't happen with either Artifacts or Supplementaries on its own.

**Comment by mezz** [comment]
This issue has been resolved in JEI:
* https://github.com/mezz/JustEnoughItems/issues/3460
