### ISSUE TITLE
[CRASH] On load, Forge 1.20

### ISSUE THREAD

**Issue by Villanueva-Flavio** [ochotonida/artifacts#251]
Hello, I was trying to create a modpack for Forge 1.20.2, I added this mod for 1.20.1 (I saw that usually they run in these sub versions)
I installed all the required mods, and i noticed that if the libraries surpass the minecraft version of what this mod was meant, it will throw this error:

[crash-2024-03-20_19.14.27-fml.txt](https://github.com/ochotonida/artifacts/files/14673168/crash-2024-03-20_19.14.27-fml.txt)

![image](https://github.com/ochotonida/artifacts/assets/78744163/96ff2521-6e7e-4035-9711-0db024186838)

I tried to fix that using a previous version so they dont surpass artifacts 1.20.1 version
Now it crashes without crash-report, this is my [latest.log](https://github.com/ochotonida/artifacts/files/14673178/latest.log)
and this is my [debug.log](https://github.com/ochotonida/artifacts/files/14673182/debug.log)

**Mods loaded:**

1. AmbientSounds_FORGE_v5.2.22_mc1.20.1.jar
2. architectury-9.2.14-forge.jar
3. artifacts-forge-9.3.0.jar
4. cloth-config-11.1.118-forge.jar
5. CreativeCore_FORGE_v2.11.5_mc1.20.2.jar
6. cristellib-1.1.5-forge.jar
7. curios-forge-5.7.2+1.20.1.jar
8. DistantHorizons-2.0.1-a-1.20.2.jar
9. geckolib-forge-1.20.2-4.3.1.jar
10. naturalist-forge-4.0.3-1.20.1.jar
11. swl-0.2.1g-mixin-forge-1.20.1.jar
12. tectonic-forge-1.20-v2.2.1.jar
13. Towns-and-Towers-1.11.1-Fabric+Forge.jar
14. YungsApi-1.20-Forge-4.0.4.jar
15. YungsBetterMineshafts-1.20-Forge-4.0.4.jar

I hope this information is enough but, tell me if you need more!

**Comment by ochotonida** [comment]
There currently aren't any versions of Artifacts that are compatible with 1.20.2 or above, you'll have to use 1.20.1 if you want to play with Artifacts.

**Comment by Villanueva-Flavio** [comment]
My bad i think it was curios api thing
