### ISSUE TITLE
[Suggestion] Amend the snorkel tootip.

### ISSUE THREAD

**Issue by Kevin-Marsh** [ochotonida/artifacts#252]
The snorkel currently says that it allows you to breathe underwater. This implies to the players that it will grant permanent water breathing. This however isn't the case as it provides 15 seconds of water breathing and doesn't renew until the player is above water again. Would it be possible to amend the tooltip to say "Provides 15 seconds of water breathing when the player goes underwater." or something to that effect to make it clear that it isn't a permanent effect.

**Comment by ochotonida** [comment]
Thanks for the suggestion! I've updated the snorkel tooltip to better reflect this in version 9.4.0, although the specific duration isn't mentioned to stay consistent with other artifacts.
