### ISSUE TITLE
[1.20.1] Crash with latest version of Radium Reforged

### ISSUE THREAD

**Issue by Starexify** [ochotonida/artifacts#254]
**Describe the bug**
When I install the latest Radium Reforged version alongside Artifacts. They crash

**To Reproduce**
1. Download Artifacts and Radium Reforged together
2. Startup Crash

**Game Environment**

 - Artifacts: artifacts-forge-9.3.0
 - Forge: 47.2.21
 - architectury-9.2.14-forge
 - cloth-config-11.1.118-forge
 - curios-forge-5.7.2+1.20.1
 - radium-mc1.20.1-0.12.3+git.e2cf570

**Logs**
I get only a latest log. Nothing more. On their own the mods work. But together they crash
[latest.log](https://github.com/ochotonida/artifacts/files/14815901/latest.log)

**Comment by Looxond** [comment]
Can confirm

**Comment by ochotonida** [comment]
Should be fixed by Radium Reforged's latest update
