### ISSUE TITLE
Remove hardcoded rarity from WearableArtifactItem

### ISSUE THREAD

**Issue by Vancura1337** [ochotonida/artifacts#255]
**Describe the bug**
Method getRarity() from WearableArtifactItem will always return Rarity.RARE, even if you change the rarity of the item using mods like KubeJS. In the other hand items that do not extend WearableArtifactItem, but directly extend ArtifactItem (everlasting food and umbrella) can have their rarity be changed in the same way, using KubeJS, because they don't have override method getRarity() at all. Because WearableArtifactItem already extends ArtifactItem, which already handles rarities in the constructor, I think removing getRarity() method from WearableArtifactItem will solve the issue. Thank you!

**To Reproduce**
1. Download Artifacts and KubeJS into minecraft 1.20.1 forge.
2. Make a script to change, for example, Crystal Heart's rarity to Rarity.EPIC.
3. See in-game, that the rarity stays Rarity.RARE.
4. Make a script to change non-WearableArtifactItem's rarity to Rarity.EPIC.
5. See in-game, that the rarity changes.

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: 9.3.0
 - Forge: 47.1.47

**Comment by ochotonida** [comment]
Thanks for the suggestion! Should be fixed in version 9.4.0.
