### ISSUE TITLE
Mimic chest textures doesn't work with Lootr mod

### ISSUE THREAD

**Issue by IvanInventor** [ochotonida/artifacts#258]
**Describe the bug**
Mimic chest textures doesn't work with Lootr mod. Disabling option to use texture from Lootr mod displays proper default chest texture.

**To Reproduce**
1. Install Artifacts and Lootr mods
2. Spawn mimic in the world

![2024-04-12_22 01 23](https://github.com/ochotonida/artifacts/assets/43908280/cf5e6d14-58ae-45f0-9170-07bb2a89f3ca)

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Minecraft: 1.20.1
 - Architectury: 9.2.14
 - Artifacts: 9.4.3
 - Cloth Config v11: 11.1.118
 - Fabric Api: 0.92.1
 - Lootr: 0.7.30.77
 - Trinkets: 3.7.2

**Comment by ochotonida** [comment]
Lootr changed the location of their chest texture not too long ago, but this change hasn't made it to Fabric yet. This meant that fixing it for the Forge version of Artifacts broke it on the Fabric version. The next update for the Fabric version of Lootr will fix this, so it's not really worth fixing on my end.
In the meantime, you can either set `useModdedMimicTextures` to `false` in the client config, or downgrade Artifacts to version 9.4.0.

**Comment by IvanInventor** [comment]
Yeah, so commit `9d7d87d2cd0e3548cc6ed265448c15f63a5a0bff` breaks it, and here's a table of versions of artifacts/lootr i used for testing

| Works with ... | Lootr via modmamager | Lootr from `fabric-1.20` branch |
| ------------- | ------------- | ------------- |
| Artifacts 9d7d87 (BAD) | - | + |
| Artifacts d8c144 (GOOD) | + | - |


So there're two fixes possible (for 9.4.3):
- Downgrade to 9.4.0
OR
- Compile Lootr from `fabric-1.20` branch
