### ISSUE TITLE
[Fabric 1.20.1] Crash with Zenith Attributes (Apotheosis Fabric Port)

### ISSUE THREAD

**Issue by szunakabeats** [ochotonida/artifacts#259]
**Describe the bug**
When an Artifact is equipped and also some armor you can visit your Attributes.
![image](https://github.com/ochotonida/artifacts/assets/88375166/2e7ba007-5410-4ba2-a432-aa78412f4ed6)
![image](https://github.com/ochotonida/artifacts/assets/88375166/2028ee98-f1f6-4830-a0f1-3762519dd750)

Now when equipped with Armor and an Artifact in a Curios slot it will crash.

**To Reproduce**
1. Install the newest Artifacts Version
2. Install Zenith + Zenith Attributes
3. Equip 1 or 2 Artifacts ingame and Armor
4. Visit the Attributes

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: [artifacts-fabric-9.4.3]
 - Forge/Fabric Api: [fabric-api-0.92.0+1.20.1]

[crash-2024-04-18_23.51.24-client.txt](https://github.com/ochotonida/artifacts/files/15033615/crash-2024-04-18_23.51.24-client.txt)
[latest.log](https://github.com/ochotonida/artifacts/files/15033616/latest.log)

Also this was mentioned here : https://github.com/TheWinABagel/ZenithAttributes/issues/17

**Comment by florensie** [comment]
This can only be fixed on Zenith Attributes' side. As stated in the other issue, for now you can use an older version of Artifacts, until they support the latest one.
