### ISSUE TITLE
[Suggestion] Config option to disable shift tooltips

### ISSUE THREAD

**Issue by CalaMariGold** [ochotonida/artifacts#26]
Hey there, I'm the owner of Rebirth of the Night and we're using your mod for our next update. We're on version 1.12.2.

I'm just looking for a simple config option to remove the shift tooltips and instead make them regular tooltips for the baubles. I know this is a rather small and insignificant change, but when making it consistent with other bauble mods, small things like that are very important.

If you can not do this for some reason, would you be open to accepting a pull request from us adding in the config option? Thank you!

Mari

**Comment by ochotonida** [comment]
I wasn't really planning on updating the 1.12 version of this mod anymore, but because it's such a simple request I didn't really mind :p. I've uploaded a patch to curseforge
