### ISSUE TITLE
Support for 1.20.4?

### ISSUE THREAD

**Issue by Vortigern-The-Grey** [ochotonida/artifacts#260]
Tried loading with Fabric on 1.20.4, this happened:
![image](https://github.com/ochotonida/artifacts/assets/152357748/f5fb20e4-d070-4699-8d9b-24d6bf6b21f2)
Any chance of a release for 1.20.4 in the future?

**Comment by ochotonida** [comment]
There's currently no version of Artifacts that's compatible with Minecraft 1.20.4, but a port is still planned. I'm still working on some new stuff for 1.20.1, the updates to 1.20.4 and 1.20.5 should follow relatively soon after.

**Comment by Vortigern-The-Grey** [comment]
Would it be possible to keep this issue open as a progress tracker of sorts?

**Comment by EfficientStinkbug** [comment]
That's great news, 1.20.4 fabric is what I'm currently playing at. I'll keep the notifications turned on, this mod has always been on of my favourites when I played on forge :)

**Comment by ochotonida** [comment]
Just released the update for 1.20.1, 1.20.4 should follow soon. 1.20.5 will take a bit longer, since Curios and Trinkets haven't updated yet.

**Comment by ochotonida** [comment]
Artifacts version 10.0.0 is now available for Minecraft 1.20.4. The Fabric version is still under review on CurseForge, you can get it on Modrinth in the meantime.

**Comment by EfficientStinkbug** [comment]
Let's goooo, thank you!
