### ISSUE TITLE
Item not loading in mulitplayer [1.20 / Forge]

### ISSUE THREAD

**Issue by NilsIgris** [ochotonida/artifacts#261]
Hello !

In solo, the mod is perfectly working but in our server the item appear with the good appareance but their name are just "minecraft:air"
They have no description also no effect and we cant use them.
There is no error in console also no crash seems to append.

Configuration : 
- Minecraft 1.20.1
- Cloth Config 11.1.118
- Architectury 9.2.14
- Artifacts 9.4.2
- Forge 47.2.21

Have a good day and thank you for the help :D

**Comment by ochotonida** [comment]
Could you send a latest server log anyways? There might still be some useful information in there.

**Comment by NilsIgris** [comment]
[latest.log](https://github.com/ochotonida/artifacts/files/15079737/latest.log)

Here you go,
Not sure if you have anything you wanted in it so in case tell me if you need any further information. Thanks again for the fast reply and good luck with this issue :)

**Comment by ochotonida** [comment]
Just to be sure, could you double check that you also have Artifacts installed on the server? From your log it seems like that might not be the case.

**Comment by NilsIgris** [comment]
Artifact wasnt on the server yes...

Sorry for taking your time for such a stupid issue T-T
We uploaded it and everything works fine for now

Thanks you for everything !

**Comment by ochotonida** [comment]
No problem, you're not the first person to have this happen to :p
Forge allows clients to join servers as long as the client has all the mods that are on the server. While that's sometimes useful, It can lead to issues like this where it's not clear why a mod isn't working.
