### ISSUE TITLE
[1.20.1 Fabric] Incompatible mining speed mixin

### ISSUE THREAD

**Issue by TelepathicGrunt** [ochotonida/artifacts#263]
Artifact's digging claw mixin into Player Entity is incompatible with my Bumblezone mod's mixin. My mixin's goal is to increase mining speed on certain blocks if the player has Comb Cutter enchantment on their item. I do this with a ModifyReturnValue mixin from MixinExtras. 
https://github.com/TelepathicGrunt/Bumblezone/blob/1.20-Arch/fabric-base/src/main/java/com/telepathicgrunt/the_bumblezone/mixin/fabricbase/entity/PlayerMixin.java#L49

The issue is Artifact's mixin here is an inject at return with setting the setReturnValue always which effectively a cancel always.
https://github.com/ochotonida/artifacts/blob/cd128cd2f4ed878a7223201c13dc892872694508/fabric/src/main/java/artifacts/fabric/mixin/item/wearable/diggingclaws/PlayerMixin.java#L35

Looking at the mixin output class, you can see how because Artifacts is always calling setReturnValue unconditionally, it will always set isCancelled to true and take the Artifacts value while never running the Bumblezone mixin ever
![image](https://github.com/ochotonida/artifacts/assets/40846040/5e1d7a2a-a8e6-45f5-ad15-913c02a410b7)

Thus causing incompatibility with my mod. I strongly recommend switching to ModifyReturnValue like me as ModifyReturnValue is safer and allows stacking properly. An inject with an unconditional cancel/setting value is worse than an overwrite because the incompat is much harder to find. If you do inject, always add an if statement of some sort of narrow condition if you much cancel/set a value in an inject. Otherwise, ModifyReturnValue is the proper solution here

**Comment by florensie** [comment]
Thanks for reporting this. A lot of Artifact's mixins have been around since before mixin extras. I'll do a quick review of every mixin, and replace with compatible alternatives where possible.

**Comment by ochotonida** [comment]
Fixed in update 9.5.0.
