### ISSUE TITLE
power glove not adding damage?

### ISSUE THREAD

**Issue by Hargirl567** [ochotonida/artifacts#266]
When i adjusted the power glove damage to be 5 instead of 4, it simply made the glove stop working completely

Go to ingame server config provided by configure, change power glove damage to 5 instead of 4. reload the world to confirm. it no longer works?

forge 1.19.2

**Comment by Hargirl567** [comment]
uninstalled and reinstalled the mod, same issue still :/

**Comment by ochotonida** [comment]
I can't seem to reproduce this issue, so it might be a compatibility issue with another mod you have. Does this also happen with other artifacts that modify player attributes, like the feral claws and flippers? Does unequipping and re-equipping the glove do anything?
A latest.log file might also help.

**Comment by Hargirl567** [comment]
It does not happen with any other items, and no unequipping snd equipping does not do anything :(. I will attach a log file asap.

**Comment by ochotonida** [comment]
Before sending your latest.log file, could you execute `/data get entity @p` as a command, once with the glove equipped and once without? That should add some useful information to the log that might help debug this.

**Comment by Hargirl567** [comment]
okay, i executed those commands. im also going to try and create a new world and see if its an all around bug or incompatibility, or just with my one world. 

[latest.log](https://github.com/ochotonida/artifacts/files/15144547/latest.log)

**Comment by Hargirl567** [comment]
okay. i think i found the issue. i have the mod identity, which lets you switch to different mobs. if i stay as the player, it tacks on the effects of the power glove. but if im an allay, or vex, or any other mob, it only defaults to their base attack damage. im not sure if thats something you want to add compatibility with, or if youre even able, but thats the only issue i could seem to find.

**Comment by ochotonida** [comment]
Artifacts uses an attribute modifier to increase the player's attack damage, but it seems like Identity ignores the attack damage attribute under some conditions. The same issue can be reproduced without Artifacts by using the `/attribute` command, so it's is something that would have to be fixed on Identity's side. .
