### ISSUE TITLE
Eating On Grass Has Bone Meal Effect

### ISSUE THREAD

**Issue by Korveyus** [ochotonida/artifacts#269]
**Bug Description**
When eating food on grass it has a bone meal effect. I specifically was eating carrots, but it doesn't seem to matter what food it is. This only happens with the newest version, 9.5.0, as reverting back to 9.4.2 fixes it. This is for Forge on the 1.20.1 Minecraft version.

**Game Environment**
*Artifacts: 9.5.0
*Forge: 47.2.30

**Comment by ochotonida** [comment]
Thanks for the report! This is an effect that's only supposed to be active when the Rooted Boots are equipped, I've just uploaded a patch that fixes this. It might take some time before it's approved on CurseForge, in the meantime you can get it on Modrinth.
