### ISSUE TITLE
Mimic's entity texture incompatibility with the Lootr mod

### ISSUE THREAD

**Issue by ghost** [ochotonida/artifacts#273]
### Hey,

So I recently stumbled upon a bug that seems to affect the Mimic's entity texture, after some testing I figured it was the Lootr mod that caused this issue, It seems that the Mimic is trying to get the Lootr's chest texture but ultimately fails and leaves us with a missing texture instead

To reproduce the bug, it is as simple as loading into a new world and spawning in a Mimic or finding it naturally spawning around the world

Minecraft version: **1.20.1**
Mod loader API versions:

- **Forge: 47.2.17**
- **Fabric: 0.15.10**

But it seems to occur on any of the current Forge/Fabric API versions that the mod was built on

Artifacts version: **Release / 9.5.2**
Lootr version:  **Release / lootr-1.20-0.7.31.78**

Link to the Modrinth page of the Lootr mod
https://modrinth.com/mod/lootr

Mimic in the wild
![MimicBug](https://github.com/ochotonida/artifacts/assets/153381562/5eace533-7ef1-46e1-9d57-20f245bf2d72)

Without Lootr
![2024-04-30_13 53 09](https://github.com/ochotonida/artifacts/assets/153381562/eb681015-551f-43da-acc1-75d14f214cce)

With Lootr
![2024-04-30_13 54 28](https://github.com/ochotonida/artifacts/assets/153381562/8db53946-796f-4767-ba56-577339fe08dd)

**Also, I'm aware that I seem to have missed the 'Compatibility' label in my post, but I'm not able to add it sadly**

**Comment by ochotonida** [comment]
Thanks for the detailed report!
Lootr changed the location of their chest texture a while back, causing an issue like this, so I had to update Artifacts to use this new texture location when Lootr is loaded. While this issue should no longer happen with the latest versions of Artifacts and Lootr, it looks like the Modrinth page of Lootr is running a few versions behind.
You'll have to ask the Lootr dev(s) to update their Modrinth page such that the latest version can be downloaded there as well. In the meantime, you can either download the latest version of Lootr from CurseForge, or set the `useModdedMimicTextures` config option to `false` in the Artifacts client config.

**Comment by ghost** [comment]
Ah, alrighty, that makes sense! Thank you so much for the wonderful insight on the issue, I'll be sure to keep that in mind next time I decide to use both mods, thank you!
