### ISSUE TITLE
Is the artifacts using porting lib?

### ISSUE THREAD

**Issue by UnnamedWei** [ochotonida/artifacts#274]
**Describe the bug**
After update the artifacts the newest version, the server keeps reporting missing attributes about porting lib

**Comment by ochotonida** [comment]
The latest version of Artifacts does not use or include Porting Lib. Could you provide a log file so I can take a look at the error?

**Comment by UnnamedWei** [comment]
Thanks I will testit later

Wouter Pauwels ***@***.***>于2024年5月2日 周四01:52写道：
