### ISSUE TITLE
Minecraft Crashes when I open a chest that has a mod item in it

### ISSUE THREAD

**Issue by EternalDrifter** [ochotonida/artifacts#275]
**Describe the bug**
Minecraft Crashes when I open a chest that has a mod item in it. The same goes for breaking the chest. An attempt to extract items from the chest using other blocks (for example, hopper) also leads to a crash.
When taking items from the inventory of the creative, there is no crash, everything works fine. When removing the mod, the chests that previously crashed the game open normally - they are just empty.

Initially, the problem arose in its own assembly, but it was repeated during point verification and attempts to reproduce it in conditions without any other mods, except for those necessary for Artifacts Mod (Curios API, Cloth Config API and Architectury API)

**To Reproduce**
1. Go to any village
2. Click on chest by Right Mouse Button to open it **OR** try to break chest block **OR** try to remove objects with a hopper
3. The game freezes, the "process is not responding"
5. See your error in _.minecraft\crush-reports_

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: version 7.0.0
  - Forge 1.20.1, version 47.2.20
 - I am attaching a crash report for detailed coverage of the error

[crash-2024-05-02_15.51.14-server.txt](https://github.com/ochotonida/artifacts/files/15185347/crash-2024-05-02_15.51.14-server.txt)

**Comment by ochotonida** [comment]
Please make sure you're using the latest version of a mod before reporting issues. You mention you're using version 9.5.3, but according to your log the version you actually have is 7.0.0. That version in particular is almost a year old, and received a patch fixing this issue on the same day it released.

**Comment by EternalDrifter** [comment]
> Please make sure you're using the latest version of a mod before reporting issues. You mention you're using version 9.5.3, but according to your log the version you actually have is 7.0.0. That version in particular is almost a year old, and received a patch fixing this issue on the same day it released.

I'm sorry, I honestly have no idea why Modrinth decided to give me 7.0.0 when I was looking for this mod
