### ISSUE TITLE
Artifacts crashing with some mods 

### ISSUE THREAD

**Issue by knownasmdf** [ochotonida/artifacts#277]
I have a bunch of mods and they work fine alone buit when I try to put artifacts minecraft crashes. 

heres the crash report: 
[crash-2024-05-03_15.48.38-client.txt artifacts.txt](https://github.com/ochotonida/artifacts/files/15201682/crash-2024-05-03_15.48.38-client.txt.artifacts.txt)

 - Artifacts: [version]1.20 9.4.2
 - Forge/Fabric Api: [version] 47.2.30

**Comment by ochotonida** [comment]
For some reason Oculus crashes the game and eats the actual error anytime a mod fails to load. Removing it should tell you what the actual issue is. You're probably just missing a dependency, make sure you have Curios, Architectury API and Cloth Config installed.

**Comment by knownasmdf** [comment]
That was it! Thank you so much, now I know oculus just blocks the crashe report.

TY!!
