### ISSUE TITLE
night vision goggles - toggles not working

### ISSUE THREAD

**Issue by KEJWII** [ochotonida/artifacts#281]
So yes
It's about Night Vision Goggles
When I put them on, Night Vision Effect works
When I want to turn off Effect, the effect is still despite the fact that I switched

 - Artifacts: 9.5.5
 - Fabric Api: 1.20.1
 
other mods:
 - architectury-9.2.14
 - cloth-config-11.1.118-fabric
 - fabric-api-0.92.1+1.20.1
 - trinkets-3.7.2

Pictures:
![Base Profile Screenshot 2024 05 23 - 11 52 04 14](https://github.com/ochotonida/artifacts/assets/106697974/6418880c-3e7f-4c91-b49a-5e3508238c71)
![Base Profile Screenshot 2024 05 23 - 11 52 11 30](https://github.com/ochotonida/artifacts/assets/106697974/ecd8555b-76cd-4aa7-9c32-369efb60bd0d)
![Base Profile Screenshot 2024 05 23 - 11 52 22 83](https://github.com/ochotonida/artifacts/assets/106697974/c732af86-cafc-4027-a062-f8d42dfa30a2)

**Comment by ochotonida** [comment]
Right-clicking the item disables the cosmetics of the item, it doesn't disable the effects. It is possible to set a keybind for the night vision goggles in the vanilla keybinds menu however, which allows you to toggle the item on and off without having to unequip it manually.

**Comment by KEJWII** [comment]
Can you know what the default shortcut key is?
because I honestly did not find anything in the keyboard shortcuts

**Comment by KEJWII** [comment]
Ok i See
sorry
BTW, thank you for this important for me mod and item
