### ISSUE TITLE
Change the values of Artifact modifiers?? Crystal Heart ->only +4 hearts?

### ISSUE THREAD

**Issue by Peacuch** [ochotonida/artifacts#282]
I was looking for a way to set the Crystal Heart to give only 4 extra hearts instead of the default 10.

I apologize for being really new to modding and coding, so you might have to explain how to do it like you're talking to a toddler.

**Comment by ochotonida** [comment]
Artifacts allows the effects of items to be modified, but how you do this exactly depends on which Minecraft version and mod loader you're using. For Minecraft 1.20, you can do this using the game rules artifacts adds. For the Crystal Heart specifically, executing the following command should do what you want: `/gamerule artifacts.crystalHeart.healthBonus 8`. There's various other game rules you can use, you can find a list of them here: https://github.com/ochotonida/artifacts/wiki/Game-Rules.

Older versions of Artifacts for Forge have item specific configurations in the server config file instead. Server config files are per-world, you can find the server config file in the `serverconfigs` folder in your save folder. To find your saves you'll have to locate where your Minecraft instance is located first, this depends on the launcher you're using.

Older versions for Fabric unfortunately do not have item-specific configuration options.

**Comment by Peacuch** [comment]
HEY! Thank you for getting back to me on this! That was exactly what I need! I had no idea there were commands for this, this is perfection!!
