### ISSUE TITLE
Rendering Umbrella item

### ISSUE THREAD

**Issue by JuicyAcorns** [ochotonida/artifacts#283]
**Describe the bug**
Trying to view the artifacts tab in creative mode or through JEI crashes the game because of a rendering issue with the umbrella artifact. I can find other artifacts and use them perfectly but I have to rely on RNG or spawn them in manually to use them. I have yet to find the umbrella in a chest but I'm guessing it will crash my game as well

**To Reproduce**
1. Go to Creative mode
2. In the Creative search tab type in "umb"
3. See error

**Game Environment**
 - Artifacts: 9.5.5
 - Forge/Fabric Api: 0.88.1
https://github.com/ochotonida/artifacts/files/15475035/crash-2024-05-28_14.16.15-client.txt

**Comment by ochotonida** [comment]
Updating Fabric API to a more recent version should fix this.
