### ISSUE TITLE
Newest Lootr update breaks Mimic textures

### ISSUE THREAD

**Issue by brisingraerowing** [ochotonida/artifacts#284]
**Describe the bug**
New Lootr update breaks mimic texture

**To Reproduce**
1. Install Artifacts and newest Lootr
2. Summon Mimic
3. Broken Texture

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: 1.19.2-5.0.5
 - Forge: 43.3.8
 - Lootr: 0.4.28.72

**Comment by brisingraerowing** [comment]
![2024-05-30_11 36 43](https://github.com/ochotonida/artifacts/assets/250409/7318dc10-3af1-47fd-8b53-a026604e43db)

**Comment by ochotonida** [comment]
Thanks for the report, should be fixed in version 5.0.6.

**Comment by brisingraerowing** [comment]
Sounds good. I love this mod.
