### ISSUE TITLE
Please port all latest update for 1.19.2 Forge

### ISSUE THREAD

**Issue by kitovoi111** [ochotonida/artifacts#287]
Please port all latest update for 1.19.2 Forge

**Comment by kitovoi111** [comment]
Very need <3

**Comment by ochotonida** [comment]
Unfortunately I simply don't have the time to actively maintain Artifacts for that many Minecraft versions. Many of the new additions also rely on features only available in more recent Minecraft versions, meaning that backporting everything would be a considerable effort, if it's even possible at all.
