### ISSUE TITLE
1.20.6 Fabric cooldown artifact description is not displayed

### ISSUE THREAD

**Issue by kitovoi111** [ochotonida/artifacts#290]
I indicated cooldown with a cross at 30 seconds, but it was not displayed on the cross itself (indicated on the server side)
![image](https://github.com/ochotonida/artifacts/assets/147491823/de5c6efb-c06d-4d31-a016-821824947961)

**Comment by kitovoi111** [comment]
The server part does not send the cooldown settings for the artifact to the client; when I configured the cooldown for the artifact, I do not see it in the description.

**Comment by kitovoi111** [comment]
I tried to do it on the client side - the same problem.

**Comment by ochotonida** [comment]
Fixed in version 11.0.2
