### ISSUE TITLE
Fabric 1.20.6 - very BUG (Digging Claw attributes on all players without artifacts)

### ISSUE THREAD

**Issue by kitovoi111** [ochotonida/artifacts#292]
Having created a world in a single player game or on a server, I can break stone and other blocks with my hand and they fall out.

**Comment by kitovoi111** [comment]
I tested the build without the artifact mod and it doesn't work. When I installed the artifact mod, stones and other blocks are broken by hand (without artifacts equipped) and blocks fall out (stones, etc.)

**Comment by kitovoi111** [comment]
Minecraft version: 1.20.6
Loader: Fabric
Mod version: Artifacts Fabric 11.0.2

**Comment by ochotonida** [comment]
Thanks for the report, should be fixed in version 11.0.3.
