### ISSUE TITLE
Client disconnected with reason: Network Protocol Error

### ISSUE THREAD

**Issue by seriousfreezing** [ochotonida/artifacts#294]
I'm trying to play in my modpack and when I re-enter my world it gives this error.
I manage to enter the world for the first time, but when I leave and try to enter it just shows this error

**Game Environment**
 - Artifacts: 11.0.3
 - Forge/Fabric Api: 0.100.2
 - If you want, I'll send you the modpack for testing

https://paste.atlauncher.com/view/6b20e935-0c37-47c2-a116-c9c119cbbe3c

**Comment by ochotonida** [comment]
Thanks for the report, version 11.0.4 should fix this issue.
