### ISSUE TITLE
Mimic textures gets break with newest Lootr

### ISSUE THREAD

**Issue by LanceLuckiest** [ochotonida/artifacts#296]
**Describe the bug**
New Lootr breaks the mimic texture

**To Reproduce**

1. Steps to reproduce the behavior:
2. Install Artifacts and newest Lootr
3. Spawn Mimic
4. You'll see the broken texture

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.

 - Artifacts: 1.18.2-4.2.3
 - Forge: 1.18.2 - 40.2.21
 - Lootr: 1.18.2-0.3.29.71

**Comment by V972** [comment]
Lootr 0.3.28.70 also has this problem.  

Looks like this:     
![image](https://github.com/user-attachments/assets/dc4a5330-1b38-4c01-a9cb-d3197c88a87e)

**Comment by twoface99** [comment]
I'm having the same issue.

Disabling Lootr textures in Artifacts and Lootr is a workaround.

**Comment by ochotonida** [comment]
Fixed in version 1.18.2-4.2.4
