### ISSUE TITLE
Artifacts on 1.18.2 fails to load

### ISSUE THREAD

**Issue by Iker21dev** [ochotonida/artifacts#298]
I think the mod crashes with another mod when loading the game, I'm not sure. 
I also think this may be incompatibility, maybe cold sweat mod has something to do with their most recent betas.
 - Artifacts: 1.18.2-4.2.3.jar
 - Forge: 40.2.9
 - [other relevant mods...]: ColdSweat-2.3-b04e
[crash-2024-07-10_10.50.58-client.txt](https://github.com/user-attachments/files/16165491/crash-2024-07-10_10.50.58-client.txt)
![image](https://github.com/ochotonida/artifacts/assets/80030992/0437d7f5-9824-43f0-8c44-ec3ba15bb889)

**Comment by ochotonida** [comment]
Apologies for the delay, should be fixed in version 4.2.4
