### ISSUE TITLE
Artifacts 1.21 Fabric (pocket_piston no working)

### ISSUE THREAD

**Issue by kitovoi111** [ochotonida/artifacts#303]
Artifacts 1.21 Fabric (pocket_piston no working)

**Comment by kitovoi111** [comment]
![image](https://github.com/user-attachments/assets/67bf2881-dd42-4c38-a8f6-c096eb2763a6)

**Comment by kitovoi111** [comment]
No working.

**Comment by ochotonida** [comment]
There's currently no released version of Artifacts for Minecraft 1.21. Also, please fill in the issue template next time, it's not at all clear what isn't working.
