### ISSUE TITLE
Support Accessories over Trinkets/Curios

### ISSUE THREAD

**Issue by Bruhnanza** [ochotonida/artifacts#304]
Trinkets is Fabric-only, Curios API is (Neo)Forge-only, but there's a new mod called [Accessories](https://modrinth.com/mod/accessories) which is cross-compatible with Fabric & NeoForge and offers a wide array of features.

I believe you should consider implementing this mod for 1.21 and future versions as this mod as seen more development activity than the others, and would also simplify things for you & users as both the Fabric & NeoForge versions could use Accessories.

**Comment by ochotonida** [comment]
I'm aware that Accessories exists, but right now it's not nearly widely adopted enough for me to consider switching to it. Since Accessories contains a Trinkets/Curios compat layer, users already have the option to switch to Accessories themselves.

**Comment by SamHammie** [comment]
@ochotonida Please consider reopening this issue. It's been half a year and Accessories is currently a lot more widely adopted in the modding scene.
