### ISSUE TITLE
[Bug] [1.21 Fabric] [Item: artifacts:pocket_piston no working]

### ISSUE THREAD

**Issue by kitovoi111** [ochotonida/artifacts#305]
Fabric 1.21
Trinkets version: trinkets-3.10.0.jar
Artifacts version: artifacts-fabric-11.0.4.jar & https://github.com/ochotonida/artifacts/tree/1.21.x

1. Equip item artifacts:pocket_piston and hit other players or mobs.
2. The artifact does not work, there is no knockback.

**Comment by kitovoi111** [comment]
I test new release version 1.21 fabric, problem no fixed.

**Comment by ochotonida** [comment]
After some testing, I still can't reproduce this issue myself. The pocket piston uses the vanilla knockback attribute, and the same logic that applies the pocket piston's attribute modifier is used by many other artifacts, so either you have another mod that messes with the knockback attribute or it isn't actually broken. Keep in mind that the pocket piston doesn't apply a crazy amount of knockback, so it could be that it's there but you're just not noticing it. You can try increasing the knockback dealt by the pocket piston in the config, this might resolve your problem.
