### ISSUE TITLE
The Bug is weird that creating a world disconnects it.

### ISSUE THREAD

**Issue by makumaku1974** [ochotonida/artifacts#307]
**Describe the bug**
1.21 port could be buggy for now, it disconnected after creating a world. 

**To Reproduce**

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: [version]
 - Forge/Fabric Api: [version]
 - [other relevant mods...]

**Comment by ochotonida** [comment]
Could you provide a log file and verify you're using the latest version of NeoForge/Fabric and Artifacts' required dependencies? I'm unable to reproduce this myself.

**Comment by makumaku1974** [comment]
Ill be giving you the logs later once i tested minecraft again.

Ps. I dont really know what to find but here is the log you asked. https://mclo.gs/AiJs3pi

**Comment by Tanjiraaaaa** [comment]
I have this issue as well
However, it might be also important to note that my world was me trying to update from 1.20.6 to 1.21

**Comment by makumaku1974** [comment]
> I have this issue as well However, it might be also important to note that my world was me trying to update from 1.20.6 to 1.21

have you made a backup...

**Comment by Tanjiraaaaa** [comment]
> > I have this issue as well However, it might be also important to note that my world was me trying to update from 1.20.6 to 1.21
> 
> have you made a backup...

Thankfully, yes

**Comment by Tanjiraaaaa** [comment]
But well, it works fine after I remove the mod from my modlist
Edit: I was using the newest version of Artifacts, I used it with a large modpack that I created myself.
       Here are the [details](https://mclo.gs/zgnuYwA)

**Comment by makumaku1974** [comment]
Good for you I guess i'll be always stuck on this certain seed. -1024979035

**Comment by ochotonida** [comment]
This issue seems to happen when another mod includes a more recent version of NightConfig than the one Artifacts was built with.
Did either one of you make any changes to the config before this issue occurred? If you did, deleting Artifacts' config files should fix this. Using the in-game config screen to make changes shouldn't cause any issues.

**Comment by Tanjiraaaaa** [comment]
> This issue seems to happen when another mod includes a more recent version of NightConfig than the one Artifacts was built with. Did either one of you make any changes to the config before this issue occurred? If you did, deleting Artifacts' config files should fix this. Using the in-game config screen to make changes shouldn't cause any issues.

No I didn't change the config in any way.

**Comment by Tanjiraaaaa** [comment]
But I will try to delete its config file and try again!

**Comment by ochotonida** [comment]
Update 12.0.2 should fix this issue.

**Comment by Tanjiraaaaa** [comment]
Deleting the config file actually fixed this issue for me.
It's strange though because I don't think I tampered with it in any way before.
