### ISSUE TITLE
Crash adding Shrink Amulet to accesories slot

### ISSUE THREAD

**Issue by LilFaker** [ochotonida/artifacts#309]
The game automatically crashes when adding the amulet to the corresponding slot.
Via NbtExplorer I removed the necklace from the slot and it did not crash when loading the world but the player remains at a smaller scale.

Pastebin latest log [https://pastebin.com/e8kU9JPt](url)

**Comment by LilFaker** [comment]
The error that minecraft launcher gives is: The game crashed whilst unexpected error
Error: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 8

**Comment by ochotonida** [comment]
This crash is unrelated to Artifacts, it's a compatibility issue between Inventory HUD+ and Accessories. This crash seems to happen when equipping any curio, I managed to reproduce it myself with Charm of Undying.

**Comment by Dragon-Seeker** [comment]
True the blame is accessories for this one, noticed such and comes down to a mixin within the living entity that leads to such crashing out. Just going to disable such unless really needed by someone down the road.

**Comment by Dragon-Seeker** [comment]
> The game automatically crashes when adding the amulet to the corresponding slot. Via NbtExplorer I removed the necklace from the slot and it did not crash when loading the world but the player remains at a smaller scale.

@LilFaker I did upload a fix for such on both Curseforge and Modrinth that stops the crash from happening
