### ISSUE TITLE
Artifact Rarities

### ISSUE THREAD

**Issue by chonkyman** [ochotonida/artifacts#315]
### $${\color{#8B8B8B}Common}$$ (HEX #8B8B8B RGB 139, 139, 139): 
 - Whoopee Cushion

###  $${\color{#3CE528}Uncommon}$$ (HEX #3CE528 RGB 60, 229, 40):
 - Umbrella 
 - Snorkel
 - Charm of Sinking
 - Cowboy Hat
 - Angler's Hat
 - Scarf of Invisibility 
 - Bunny Hoppers
 - Flippers
 - Kitty Slippers
 - Snowshoes
 - Rooted Boots
 - Strider Shoes

###  $${\color{#2872E5}Rare}$$ (HEX #2872E5 RGB 40, 114, 229):
* Night Vision Goggles
* Villager Hat
* Panic Necklace
* Lucky Scarf
* Thorn Pendant
* Helium Flamingo
* Obsidian Skull
* Digging Claws
* Feral Claws
* Fire Gauntlet
* Flame Pendant
* Pocket Piston
* Onion Ring
* Aqua-Dashers
* Running Shoes
* Steadfast Spikes

###  $${\color{#5D28B9}Epic}$$ (HEX #5D28B9 RGB 93, 40, 185):
* Cross Necklace
* Shock Pendant
* Antidote Vessel
* Chorus Totem
* Golden Hook
* Power Glove
* Vampiric Glove
* Pickaxe Heater
* Withered Bracelet

###  $${\color{#E1B211}Legendary}$$ (HEX #E1B211 RGB 225, 178, 17):
* Everlasting Beef / Eternal Steak
* Cloud in a Bottle
* Crystal Heart
* Universal Attractor

### Unknown Category:
* Charm of Shrinking (I really have no idea)
* Warp Drive (Rare / Epic / Legendary ?)

**Comment by ochotonida** [comment]
I personally don't think this adds much, honestly. Most artifacts are designed to be not too powerful, while still being useful to some degree. If some artifact is much more powerful than another, I'd rather change how the artifacts work to balance things out a bit.
It's also hard to define how rare an artifact is in terms of where you find them, each artifact is found in different structures so it depends a lot on your playstyle and where you look.
