### ISSUE TITLE
Incompat with Origins [Fabric 1.21]

### ISSUE THREAD

**Issue by VexInLimbo** [ochotonida/artifacts#316]
**Describe the bug**
Crash when trying to open up the mod with Origins in the modpack.

**To Reproduce**
1.Installing both mods
2.Starting the game
3.Game crashes

**Game Environment**
 - Artifacts: 12.0.5 for 1.21
 - Fabric Api: 0.16.2
 - Relevant mods: Origins 1.13.0-alpha.6

**Comment by Samakatayn** [comment]
Try a different version of origins maybe?

**Comment by ochotonida** [comment]
Fixed in version 12.0.6
