### ISSUE TITLE
How do I get eternal meat?

### ISSUE THREAD

**Issue by pil0lo** [ochotonida/artifacts#317]
How do I get eternal meat?
There is only eternal raw meat.
![1](https://github.com/user-attachments/assets/daa56504-6ebe-4c95-9c23-b3a2f4069c9c)

**Comment by jotapanden** [comment]
Easy, cook the eternal raw meat on a furnace

**Comment by Samakatayn** [comment]
For the raw one, it's a low chance to get it from a cow and just put in a furnace to turn it cooked :)
