### ISSUE TITLE
[suggestion] more option to enable disable stuff.

### ISSUE THREAD

**Issue by tealtoxic** [ochotonida/artifacts#32]
some suggestions from me:

artifacts:
- enable/disable each artifact

chest:
- loot control? (the ingots and gems are bit too much)

reason:
- i found it pretty easy to find camps and made me rich fast and op.

**Comment by draklorx** [comment]
I second this. This would be an excellent feature.

**Comment by ochotonida** [comment]
Adding/removing items based on a config option should generally be avoided, however it is still possible to change the loot in chests and artifacts dropped from mimics by overwriting this mod's loot tables with a datapack.
I'll reduce the chance to find ingots and gems in chests in the next update.

**Comment by Aizistral** [comment]
> Adding/removing items based on a config option should generally be avoided

That depends on what you mean by adding/removing. Of course you shouldn't register or not register item depending on config, and current implementation of config in Forge anyways loads your files after all of the registry events as far as I'm aware.

This suggestion however likely means options in config to allow disable individual items from being legitimately obtainable, which is a commonly seen practice among mods and would be a welcome addition to your one.
