### ISSUE TITLE
Truning off generations of camps

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [ochotonida/artifacts#321]
In 1.16.5 I had the option to blacklist the camp from being generated

```
	#List of biome IDs in which campsites are not allowed to generate
	#End and nether biomes are excluded by default
	#To blacklist all biomes from a single mod, use "modid:*"
	biome_blacklist = ["minecraft:void", "undergarden:*", "the_bumblezone:*", "twilightforest:*"]
```

I'd like to have this option back in 1.20.1 to blacklist twiligt forest from generating the camps.

**Comment by ochotonida** [comment]
This config option was made obsolete by the addition of the `minecraft:is_overworld` biome tag in Minecraft 1.19. Campsites will now only generate in biomes that generate in the overworld by default, you no longer need to blacklist biomes from specific mods yourself.
