### ISSUE TITLE
Items quick equipping into the wrong slots

### ISSUE THREAD

**Issue by JesseAsh07** [ochotonida/artifacts#325]
I've been playing ATM10 with some mates and I've been loving irons spells and spell books and use multiple books in my hot bar i just right click them to quick swap them into my spell book slot but since the update to ATM 10 right clicking any item including backpacks artifacts and jetpacks doesn't put them into their respective slots but puts them into the new "Curio" slot and instead of being able to quick swap i have to manually open my inventory and switch the books around; minor visual glitch as well they work fine once I've put them in the spell slot but visually they appear in the crafting on a stick slot as well as that the Deep Learner from Neural Networks refuses to go into its equip slot

**Comment by ochotonida** [comment]
This is not a bug, `curio` slots are special in that they can accept any item regardless of which slot they go into. Items should still work regardless of which slot they're equipped into, if not, that's likely a bug with whichever mod the item is from.
Keep in mind that the slots used by Artifacts, Iron Spells etc. aren't added by Artifacts, they're added by Curios (or [Adorned](https://www.curseforge.com/minecraft/mc-mods/adorned) in ATM10's case), so any bugs with these slots should be reported to them instead.
