### ISSUE TITLE
Crash when start dedicated server

### ISSUE THREAD

**Issue by DrSigma4164** [ochotonida/artifacts#326]
**Describe the bug**
Recently when the Relics compatibility mod came out, I updated your mod to 9.5.13 and the dedicated server stopped starting.

**To Reproduce**
1) Download Relics,
2) Download Artifacts 9.5.13,
3) Download the compatibility mod,
4) Try to start the dedicated server.
5) See error

**Game Environment**
 - Minecrft: 1.20.1
 - Artifacts: 9.5.13
 - Forge/Fabric Api: Forge 47.3.1
 - RARCompact: 0.1.5
 - Relics: 0.8.0.7
 
 Crashlog: https://gist.github.com/DrSigma4164/a73538df44033ebd2cdbfcba0a94be37

**Comment by SSKirillSS** [comment]
Hi! This is a bug on the RAR-Compat's side, and will be fixed in a few days.

**Comment by Temulla** [comment]
hi, the fix can already be downloaded on CurseForge
