### ISSUE TITLE
Crashes on startup on 1.14.4

### ISSUE THREAD

**Issue by SpencerMeow** [ochotonida/artifacts#34]
It doesn't have a crash report for it but after finally matching the dependencies with the mod the game just crashes while loading

**Comment by Aizistral** [comment]
Provide your **latest.log** file or something then. It's highly unlikely that someone will be able to help this case with no data whatsoever.

**Comment by SpencerMeow** [comment]
Alright I got it
[crash-2020-10-11_16.41.01-client.txt](https://github.com/ochotonida/artifacts/files/5362160/crash-2020-10-11_16.41.01-client.txt)
[latest.log](https://github.com/ochotonida/artifacts/files/5362161/latest.log)

**Comment by Aizistral** [comment]
You are using version of Forge that didn't have global loot modifiers backported yet. Looks like @ochotonida forgot to specify proper version dependency back in the day. Update Forge to at least 28.2.4, and you'll be fine.
