### ISSUE TITLE
Make mimics' skin compatible more chest skins

### ISSUE THREAD

**Issue by Gabo6480** [ochotonida/artifacts#38]
Through gameplay with this mod in modpacks I have found that mimics stand like a sore thumb with mods like Quark installed which add wood variants to chests.
Maybe the skin could be picked dynamically so it is way more compatible

**Comment by ochotonida** [comment]
I've tried looking into this before, but unfortunately this doesn't seem to be possible unless I manually add the chest textures for all mods I want to support to my mod. I did add a config option to prevent non-vanilla chests to be used to the 1.16.3/1.16.4 version though. I'll probably reduce the chance for modded chests to spawn in the future, or disable them altogether to solve the issue

**Comment by Gabo6480** [comment]
Then what about adding a folder where we can add the textures? Or handing us a resource pack template where we can add the textures?
