### ISSUE TITLE
Googles not rendering properly

### ISSUE THREAD

**Issue by Aflaungos** [ochotonida/artifacts#39]
In Minecraft Version 1.16.3
The Goggles artifact is rendering everything black unless I go underwater, then everything functions as normal. Text also goes black and all icons.

**Comment by ochotonida** [comment]
I can't reproduce the issue myself, and it seems unlikely to me that this issue is caused by Artifacts, as the night vision goggles simply apply the vanilla night vision effect. Could you try using a night vision potion to confirm this?

**Comment by ochotonida** [comment]
I assume this is related to [this bug](https://bugs.mojang.com/browse/MC-165208), and therefore not something I can fix
