### ISSUE TITLE
Feeding the Eternal Steak to a wolf consumes the Eternal Steak.

### ISSUE THREAD

**Issue by Tall-Bird** [ochotonida/artifacts#45]
Minecraft v1.16.4
Forge v35.1.13
Artifacts v2.7.3

Feeding the Eternal Steak to a wolf consumes the Eternal Steak.

**Comment by ochotonida** [comment]
While I probably could probably fix this in some way for wolves, there's not really a way to prevent other modded animals from consuming it, so I had to disable feeding it to animals entirely
