### ISSUE TITLE
Inventory bug 

### ISSUE THREAD

**Issue by Hukenon** [ochotonida/artifacts#46]
When there is an item selected (on cursor) and click on the extra GUI slots button in the inventory, the item disappears. I've also found a way to duplicate items using this, but clicking the button with an item after having opened the extra slots with an empty cursor- only to exit the inventory and see a duplicate kick out. I may have explained this like an idiot but you should be able to recreate it easily :)

**Comment by Hukenon** [comment]
Now realizing this is an issue with Curios API not Artifacts, sorry

**Comment by ochotonida** [comment]
No problem :p
