### ISSUE TITLE
Hostile mobs not spawning naturally

### ISSUE THREAD

**Issue by madmax3004** [ochotonida/artifacts#52]
Artifacts version: Artifacts-1.16.4-2.7.5
Forge version: 35.1.37

Hostile mobs are not spawning naturally. Neither on the surface or underground.

The only exception is a superflat world, where hostile mobs do seem to spawn, or spawning hostile mobs using spawn eggs or through spawners. Ice & Fire mobs seem to not be impacted, nor passive mobs.

Removing this exact mod from a 182 mod modpack seems to fix the issue.

**Comment by ochotonida** [comment]
Would you mind giving me a log file and your modlist? As far as I'm aware this isn't an issue when playing with just Artifacts, so there's not much I can do based on this information alone

**Comment by madmax3004** [comment]
I don't have any logs on hand, but I can give you the modpack.
Here is the modpack import file for the CurseForge launcher:
(Note that Artifacts is included but disabled)

[DynaStar Creates-Release Candidate 1.zip](https://github.com/ochotonida/artifacts/files/5872868/DynaStar.Creates-Release.Candidate.1.zip)

**Comment by AceYacce** [comment]
Hello 
  My Artifacts version is Artifacts-1.15.2-2.5.1
 My forge version is forge-1.15.2-31.2.49
And my Curios API version is curios-FORGE-1.15.2-2.0.2.7*

  The hostile mobs don't spawn for me neither, what is boring in survival. 
And I don't have any other mods on this version of forge-1.15.2
 That is  

Thank you for your reading and attention, I sincerely hope that we can fix this problem in the future.

**Comment by ochotonida** [comment]
@AceYacce would you mind giving me your full mod list? I've found this issue rather inconsistent to produce, but having your mod list as well might make it a lot easier to solve

**Comment by madmax3004** [comment]
@ochotonida I think he mentioned that he's running no other mods.

On another note:
I recently tested if this issue was still present in the pack while I was updating everything to their latest versions, and it still appears to be.

**Comment by ochotonida** [comment]
Thanks for pointing that out, I missed it when I read their comment. Though I just tested with the versions they specified, and mobs are spawning just fine for me, so there must be something they're doing different

**Comment by AceYacce** [comment]
In fact when I wrote my first message, in addition to having Artifacts-1.15.2-2.5.1, forge-1.15.2-31.2.49 and curios-FORGE-1.15.2-2.0.2.7 I used Hwyla-forge-1.10.8-B72_1.15.2, Bookshelf-1.15.2-5.6.40 and WAWLA-1.15.2-3.0.4

So, to be sure, I retested without any other mods (for real this time) except Artifacts-1.15.2-2.5.1, forge-1.15.2-31.2.49 and curios-FORGE-1.15.2-2.0.2.7 , but the aggressive mobs still do not appear (except Mimic) and I do not understand this bug. 

Could it be from a different java version than yours or an incompatible forge version?

**Comment by Whiskey-Sunshine** [comment]
I was having this same problem in a custom 1.16.5 modpack I've been making for personal use, actually, and started doing some testing to figure it out. Artifacts 1.16.5-2.8.3, Curios 1.16.5-4.0.5.1, Forge 36.1.2.

From what I've seen, mimics apply to the hostile mob cap, and even with the default configs (and a 16 chunk render distance), there are usually over 50+ mimics in range at any time, especially if you use world gen mods that provide more campsite-friendly cave generation (I use Yung's Better Caves and Quark together, which creates fairly enormous, flatter areas underground prime for campsite generation, even with defaults, I've seen clusters of campsites 3-4 big in those places).

The moment I ran /kill @e[type=artifacts:mimic], other hostile mobs began to spawn immediately. Teleporting away to areas outside of that, hostile mobs stopped until I killed every mimic again. My last kill command on mimics recorded 138 entities killed (mimic chance was reduced to 20% from 30%, campsite chance upped to 16% from 8% in configs, with a 16 render distance)

Figured I'd swing by and mention that, if that helps any.

**Comment by Whiskey-Sunshine** [comment]
As an afterthought, I do also want to mention that there also seems to be a weird interaction with Team Abnormals mods. Removing those but leaving Artifacts in allows hostile mobs to begin spawning again as well, regardless of the number of mimics present.

**Comment by ochotonida** [comment]
You're entirely right, mimics count towards the hostile mob cap. I'll release a patch as soon as possible to fix this. 
I already noticed myself that this only seems to become a problem under certain circumstances like you mention with Team Abnormals' mods, but I was never able to pin down the exact issue. (tbh I kinda dismissed mimics being a possible cause because they don't spawn like other mobs do, and I haven't made any major changes to them in a long time)

**Comment by Whiskey-Sunshine** [comment]
Ayy, happy to help! Yeah, it just occurred to me when I went on an artifact hunt in one of my worlds and noticed that hostile mobs started spawning more and more the more mimics I killed in that area, so I did some kill command testing. Lo and behold...
