### ISSUE TITLE
[1.16.5] Crashing Issue With Mimicubes

### ISSUE THREAD

**Issue by NielsPilgaard** [ochotonida/artifacts#57]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/1205

> **Describe the bug**
Entity known as Mimicube attacked me, presumably tried to transform in to me and is now causing a crash loop.
Effects at the time were levitation from a Shulker
Equipped items to my knowledge were a full set of unenchanted Archmage robes from Ars Nouveau, the Archmage book from the same mod, a DANK, and a diamond sword with 5% chance to set something on fire from Apotheosis and an umbrella from some mod with a name that escapes me.
Upon trying to rejoin the world it goes: Joining Server, Encrypting, Loading Terrain, Saving World, Crash to Launcher with error

> Friend of mine told me, after reading my crash report, the umbrella cannot be equipped by the Mimicube after it copies my gear. So from what we can see that would be the reasoning for crashing upon loading.

> **Logs**
https://pastebin.com/3K2VNPpH
```

**Comment by ochotonida** [comment]
Thanks for the report! I've released a patch that fixes the issue.

**Comment by NielsPilgaard** [comment]
Damn that was quick, thank you!
