### ISSUE TITLE
Over-generation of undeground campsites in The Undergarden dimension

### ISSUE THREAD

**Issue by noobanidus** [ochotonida/artifacts#58]
![](https://i.imgur.com/B4u2mII.jpeg)

This is using version 1.16.5-0.4.5 of the Undergarden, and 1.16.5-2.7.7 of Artifacts on Forge 1.16.4-35.1.36.

I'm not sure if campsites should be spawning in this dimension, but whatever placement is used is problematic made problematic due to the vastly open space, making standard overworld spacing not necessarily valid.

**Comment by Aizistral** [comment]
Honestly I would advise to restrict campsite generation to Overworld by default. What business they could possibly have spawning in all those modded dimensions?

**Comment by ochotonida** [comment]
It's already possible to blacklist individual biomes in the config, but for the next update I've made a change to make it easier to blacklist an entire mod and I've blacklisted the Undergarden by default

**Comment by ochotonida** [comment]
The default config options in the latest version should resolve this issue
