### ISSUE TITLE
[Suggestion] Angler's Cap

### ISSUE THREAD

**Issue by ChloeDawn** [ochotonida/artifacts#59]
It would reduce the amount of time it takes to catch something (a passive equivalent of the Lure enchantment)

**Comment by florensie** [comment]
A fishing related artifact does does sound like a good idea.

**Comment by TheDeviantCrafter** [comment]
It could allow players to catch other artifacts when fishing.

**Comment by ochotonida** [comment]
Added in version 9.5.0.
