### ISSUE TITLE
Game Crashes when changing dimensions as of latest update

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [ochotonida/artifacts#63]
Minecraft: 1.16.5
Forge: 36.0.42
Artifacts: 2.8.0
Curios: 4.0.4.0

When testing out the latest update to this mod I found that whenever I enter a nether portal or I'm in the process of changing dimensions then my game crashes. 

**Edit: I have found that this happens regardless of if I have an artifact equipped or not.** 

Latest Log: https://pastebin.com/n80fkFc6
Crash Report: https://pastebin.com/a7zfzf5M

**Comment by ochotonida** [comment]
Thanks for the report, I've uploaded a patch that should fix the issue. It should be available on curseforge in a minute or two

**Comment by The-Bernician-Lamb** [comment]
I can confirm this has fixed it! Thanks a lot!
