### ISSUE TITLE
Crash with artifacts

### ISSUE THREAD

**Issue by GeorgeOrwell1** [ochotonida/artifacts#66]
When I tried to join my single-player world, it crashed and according to [Not Enough Crashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge), it seems that your mod was causing it.

Log:
https://pastebin.com/mcFCe58c

I'm using Artifacts-1.16.5-2.8.0 with Forge 36.0.30

After further investigation, it seems that it is an incompatibility with Optifine, as it works fine without it.

**Comment by ochotonida** [comment]
Try updating Artifacts, the latest patch should fix this issue
