### ISSUE TITLE
[1.16.5]The console spawns out information

### ISSUE THREAD

**Issue by EnterFor** [ochotonida/artifacts#68]
![image](https://user-images.githubusercontent.com/10114685/108811939-2136c780-75e9-11eb-9290-bda54da5cf02.png)
When you wear Goldenhook to attack monsters, the console has been spawning messages. When you unload the jewelry, the messages disappear.

Forge：36.0.40
Mod：1.16.5-2.8.1

**Comment by ochotonida** [comment]
Thanks for the report, I put this is for debugging and forgot to take it out again :p
