### ISSUE TITLE
[Suggestion] Item description box size

### ISSUE THREAD

**Issue by luxlacis** [ochotonida/artifacts#69]
Really small thing, but could you possibly change it so that the description of the item isn't as long in the horizontal axis, please?

For example this item description goes across my whole screen: https://i.imgur.com/MPb1pmu.png. Maybe reduce it to like a 1/3 of this size?

**Comment by Aizistral** [comment]
I see some devs still haven't figured out they gotta manually split their tooltip into lines when those get too big. Still.

**Comment by ochotonida** [comment]
I've released a patch which splits this particular tooltip in two and I've added a config option to remove the tooltips altogether (they can be found in JEI now).
