### ISSUE TITLE
[Bug] Crash when JER and Stellar Sky are in a pack with artifacts

### ISSUE THREAD

**Issue by MushWolf** [ochotonida/artifacts#7]
Whenever I have the following mod list:
Artifacts - version 1.0.2
Baubles - version 1.5.2
JEI - version 0.271
Just Enough Resources (JER) - version 0.9.0.52
Stellar API - version 0.4.2.9
Stellar Skye - version 0.5.3.2

Forge version: forge-14.23.5.2824 (although this issue has existed over previous versions too)

I get a crash.

When you either disable JER or Stellar Sky there is
no issue but when both JER and Stellar Sky are active they create the following crash I added as a file.

[crash-2019-03-29_12.34.35-client.txt](https://github.com/ochotonida/artifacts/files/3022435/crash-2019-03-29_12.34.35-client.txt)

The log for the forge startup is as follows:

[latest.log](https://github.com/ochotonida/artifacts/files/3022439/latest.log)

**Comment by ochotonida** [comment]
This seems to be an issue with stellar sky I cannot fix

**Comment by ochotonida** [comment]
See MinecraftModDevelopmentMods/StellarSky#113
