### ISSUE TITLE
Main empty hand incompatibility with "FirstPersonMod"

### ISSUE THREAD

**Issue by Nebula240** [ochotonida/artifacts#70]
Hi! The main hand artifacts when the hand is empty render in a weird way, I would like to know if there's a way to make the mod compatible with FirstPersonModel: https://www.curseforge.com/minecraft/mc-mods/first-person-model/files

EDIT: This is on the latest 1.16.5 artifacts version, thanks!

Pictures here on how it's being shown:
![2021-03-11_17 35 16](https://user-images.githubusercontent.com/62150697/110852171-c4960680-8290-11eb-9742-8dfde505d24a.png)
![2021-03-11_16 59 22](https://user-images.githubusercontent.com/62150697/110852184-c9f35100-8290-11eb-9e56-71e19793e99a.png)
![2021-03-11_16 59 27](https://user-images.githubusercontent.com/62150697/110852198-cf509b80-8290-11eb-98f7-24f1efe167b8.png)
![2021-03-11_16 59 31](https://user-images.githubusercontent.com/62150697/110852215-d5467c80-8290-11eb-8fb3-a06f58c77522.png)
![2021-03-11_16 59 38](https://user-images.githubusercontent.com/62150697/110852225-db3c5d80-8290-11eb-9747-d91b60625bb2.png)
![2021-03-11_16 59 43](https://user-images.githubusercontent.com/62150697/110852249-e1cad500-8290-11eb-9556-cf1d4756d3f6.png)
![2021-03-11_16 59 52](https://user-images.githubusercontent.com/62150697/110852266-e8594c80-8290-11eb-9198-c4d79f598441.png)
![2021-03-11_16 59 57](https://user-images.githubusercontent.com/62150697/110852279-eee7c400-8290-11eb-899d-3cc31fe8259b.png)

**Comment by ochotonida** [comment]
This seems to be an issue with the First-person Model mod, I've reported it to their issue tracker

**Comment by florensie** [comment]
Also, in the mean time you can disable the glove rendering manually in the config file.

**Comment by ochotonida** [comment]
I'm gonna close this now, as it's technically an issue with first person model, and it *should* be fixed in their next release
