### ISSUE TITLE
Suggestion: config value for invisibility 2 for scarf

### ISSUE THREAD

**Issue by endigma** [ochotonida/artifacts#75]
The current scarf of invisibility gives Invisibility 1, which does not hide armor/tools/etc. I feel as though an item like this should be the real deal especially with it's rarity, offering vanish-like functionality, perhaps excluding itself. I'm not sure if this is doable, but I think it'd be a good improvement, as an option.

I'm aware this effect isn't achievable through potions, but it's occasionally used by plugins and mods for vanish purposes so I have reason to believe it exists in some regard. If not a solution similar to ess/etc vanish would be cool.

**Comment by ochotonida** [comment]
While it's definitely possible to make the player completely invisible, it's not really something I want to add to the mod right now, as a config option or not. The main point of the item is to lower the detection range of mobs (at the expense of not wearing armor), and I think it's already quite powerful in that regard.
