### ISSUE TITLE
Artifacts Crashes Modpack when alongside Canvas

### ISSUE THREAD

**Issue by toErIpNid** [ochotonida/artifacts#77]
After testing out why canvas was crashing the modpack I was making, I found out that artifacts crashes the pack when canvas is along side it for some reason. 
Fabric: 0.11.3.
Modlist: 
![current](https://user-images.githubusercontent.com/78389307/112084683-373b9780-8b57-11eb-88dc-807cd348b203.PNG)
Crashlog: 
[crash-2021-03-22_21.31.15-client.txt](https://github.com/ochotonida/artifacts/files/6186530/crash-2021-03-22_21.31.15-client.txt)

**Comment by ochotonida** [comment]
This seems to be an issue with the fabric version of this mod, I've relayed the issue here: https://github.com/florensie/artifacts-fabric/issues/25
