### ISSUE TITLE
When wearing the tiny shirt, the player becomes thinner rather than smaller unless in water

### ISSUE THREAD

**Issue by Dimentive** [ochotonida/artifacts#8]
This is a pretty strange bug. I’m not sure whether it’s a bug on Artifacts’ side or a bug on [ArtemisLib’s](https://minecraft.curseforge.com/projects/artemislib) side.

When standing in water, 
![Small](https://user-images.githubusercontent.com/34230933/55769591-a494b180-5a81-11e9-8be0-02f93ba65eed.png)

![Thin](https://user-images.githubusercontent.com/34230933/55769592-a494b180-5a81-11e9-90b9-f45563a5fd65.png)

Gameplay is unaffected; the player is still one block high. It’s purely a visual bug.

Mod list: https://pastebin.com/raw/GyfNKkxG

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2825 (latest)
* **Artifacts:** [1.1.0](https://minecraft.curseforge.com/projects/artifacts/files/2695223) (latest)
* **ArtemisLib:** [1.0.4](https://minecraft.curseforge.com/projects/artemislib/files/2693358) (latest)

**Comment by ochotonida** [comment]
Hmmm this is odd. I've had a similar issue before on my end but I had fixed that. Does this happen consistently? I can't seem to replicate the issue myself. Also, would you mind posting a log file from a session where this happens? There might be some errors in there that could indicate what's going wrong.

Also, the version of artemisLib you linked (1.0.3) is only for 1.13, I'm assuming you're using 1.0.4.

**Comment by Dimentive** [comment]
Yes, I meant [ArtemisLib 1.0.4](https://minecraft.curseforge.com/projects/artemislib/files/2693358). Sorry about that.

By the way, here’s my mod list: https://pastebin.com/raw/GyfNKkxG

I tried checking the log after equipping the tiny shirt, but there’s nothing in the log related to ArtemisLib or Artifacts—or any errors in general.

**Comment by Dimentive** [comment]
Has this been fixed?

**Comment by Dimentive** [comment]
Since this was closed, has this issue been fixed in the latest versions of the mod?

**Comment by ochotonida** [comment]
I've dropped support for the 1.12 version of this mod, and the tiny shirt does no longer exist on the newer versions

**Comment by Dimentive** [comment]
Awh :( Okay.

**Comment by Dimentive** [comment]
Awh :( ^^Okay.
