### ISSUE TITLE
Telekinesis from Wonderful Enchantments +  Luck Scarf dup itens

### ISSUE THREAD

**Issue by hadDOTpy** [ochotonida/artifacts#81]
Any broken block with an enchanted tool with Telekinesis (from Wonderful Enchantments) adds 2 of the block/item in the inventory

How to reproduce the issue:

• Enchant an pickaxe with Telekinesis
• Equip Luck Scarf on curios slot
• break a block

Wonderful Enchantments: wonderful-enchantments-1.16.4-1.1.2
Artifacts: Artifacts-1.16.5-2.8.4
Forge: 36.1.2

**Comment by ochotonida** [comment]
This seems to be a compatibility issue between Wonderful Enchantments and Curios (https://github.com/Majrusz/WonderfulEnchantmentsMod/issues/24), updating Wonderful Enchantments to the latest version (1.2) should fix this
