### ISSUE TITLE
[Suggestion] configurable (or just nerf) feral claws bonus

### ISSUE THREAD

**Issue by Jackiecrazy** [ochotonida/artifacts#83]
feral claws add 100% attack speed per claw. With two, you can swing an axe roughly as fast as your fists. Considering how powerful attack speed is (strength and the power glove benefits faster weapons much more due to their flat bonus, for instance), it may be prudent to add a config option to decrease the bonus, nerf it outright (to, say, +1 or +50% attack speed), or make two claws not stack.

**Comment by ochotonida** [comment]
Thanks for the feedback, I'll add a config option and reduce the default value a bit for the next update
