### ISSUE TITLE
[Suggestion] Umbrella protects from the rain

### ISSUE THREAD

**Issue by copperwarrior** [ochotonida/artifacts#84]
I was using this mod in conjunction with the Origins forge port as an Enderian. I finally found the umbrella after a while of searching when, to my dismay, the umbrella did not protect me from the falling rain. 

I think it would be a pretty neat subtle addition for the umbrella to prevent you from getting wet when in the rain.

**Comment by ochotonida** [comment]
This should be fixed in the next major version of Artifacts (unless Origins does some weird stuff on their end)
