### ISSUE TITLE
[Suggestion] Quark compatibility

### ISSUE THREAD

**Issue by GeorgeOrwell1** [ochotonida/artifacts#85]
As the title says, it would be cool if you added Quark compatibility in the form of firstly making the Mimic have an oak chest texture from Quark if Quark is installed (which wouldn't make it distinguishable from a randomly generated chest from Quark), and secondly making the randomly generated chest also be an oak chest from Quark instead of the vanilla chest being present.

**Comment by ochotonida** [comment]
I'll see if I can implement this as a config option. (Wooden) chests from other mods should already be able to spawn in campsites,  although you can disable this in the config if you want mimics to be harder to distinguish from actual chests.
