### ISSUE TITLE
Requiem Compatibility

### ISSUE THREAD

**Issue by Dual-Iron** [ochotonida/artifacts#86]
When possessing a mob, some artifacts simply don't work. This includes, but is not limited to, the Fire Gauntlet, Power Glove, Pocket Piston, and all the Pendants.

**Comment by ochotonida** [comment]
Hmm. Do you happen to know whether there's any artifacts that do work?

**Comment by Dual-Iron** [comment]
https://github.com/Ladysnake/Requiem/issues/326 <-- See here for the issue posted there.
Invisibility Scarf works.

**Comment by florensie** [comment]
You're using the Fabric version of Artifacts, this Github repository is for the Forge version. Please open an issue here: https://github.com/florensie/artifacts-fabric/issues
