### ISSUE TITLE
NEW ARTIFACT 

### ISSUE THREAD

**Issue by xelotex** [ochotonida/artifacts#87]
Make a new artifact for the feet that improves your control in mid air, like the flippers does when in water, and make them also act like aqua affinity but when in mid air, and you could make the artifact to give you the ability to always make the sweep attack, this would make good synergy with the cloud in a bottle, and i think no other mod has something similar to this idea, so this could make your mod even more atracktive.

**Comment by ochotonida** [comment]
While it's not exactly what you're asking for, a new Artifact allowing you to swim in the air for a short period of time has already been implemented for the next update. Since it's worn in the belt slot you can use it while wearing flippers, which will increase your swimming speed
