### ISSUE TITLE
Claw crashing my world

### ISSUE THREAD

**Issue by Klouver-github** [ochotonida/artifacts#91]
https://paste.gg/p/anonymous/865eb820eb3548e499805ecb27173cc3

anytime I use the claws in curios hotbar it crashes my world. but when I don't use it, it doesn't crash my world

**Comment by ochotonida** [comment]
Thanks for the report, I'll get it fixed as soon as possible

**Comment by Klouver-github** [comment]
Thank you! I really love this mod and I continue to love the new crazy artifacts that comes :D

**Comment by ochotonida** [comment]
I'm glad you like it! I was expecting some issues with this update with all the stuff I had to change to add more config options (despite my testing), but luckily crashes like these are usually easy to fix. 
I've uploaded a patch to curseforge that should fix the issue. (it seems curseforge took it's time to approve it though...)
