### ISSUE TITLE
[1.16.5] Crash with Hats

### ISSUE THREAD

**Issue by Ritzumi** [ochotonida/artifacts#92]
**Describe the bug**
(Client side) Game crash every time an player try to open hats interface.

**To Reproduce**
1. Join a world
2. Press hotkey to open hats interface.
3. See error

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: Artifacts-1.16.5-2.9.1
 - Forge: 36.6.16
 - Hats: Hats-1.16.5-10.2.0

Crash Log
https://gist.github.com/Ritzumi/789eeec0193895bde35858fc20e693e2

Noticed
Relics mod also had this bug before fixed in version 0.1.10.2

**Comment by ochotonida** [comment]
Thanks for the report, I'll try to get it fixed soon

**Comment by ochotonida** [comment]
I've uploaded a patch to curseforge that fixes the issue. Seems like the Relics dev and I made the same mistake :p
