### ISSUE TITLE
Compatibility - Running Shoes breaks stepup mod

### ISSUE THREAD

**Issue by SiliconAshes** [ochotonida/artifacts#96]
**Describe the bug**

There is a simple QOL mod called stepup.  It simply increases the player step height to allow the player to climb single blocks without jumping.

When Running Shoes from Artifacts-1.16.5-2.9.0 or later is equipped, stepup no longer functions.  Increased step height while sprinting still functions, but that is per Running Shoes description, and is not indicative of the problem.  Running Shoes from Artifacts-1.16.5-2.8.4 and earlier do not cause this breakage. 

**To Reproduce**
1. Install a clean 16.5 Minecraft instance, add Forge version 36.1.0, 36.1.45, 36.1.15, or likely any in between.
2. install Artifacts-1.16.5-2.9.0 or later (tested through Artifacts-1.16.5-2.9.2)
3. install StepUp-1.16.4-0.2.0, and enable (H key by default)
4. See that step up functions - can walk up single blocks w/o jumping
5. Equip Running Shoes
6. See that stepup no longer functions.  vanilla auto jump still functions, but not stepup.

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: Artifacts-1.16.5-2.9.2
 - Forge: Forge 36.1.25
 - StepUp: StepUp-1.16.4-0.2.0
 
**Additional Note**
I have seen other mods provide a similar function to stepup, either as an enchantment or (in the case of Astral Sorcery), as a perk.  Other mods that have broken stepup have also broken those.  I do not know if this affects those as well, but think it very possible.

**Comment by ochotonida** [comment]
Thanks for the report! I made some minor changes during the 2.9.0 update and apparently I got a bit too optimistic when refactoring the logic that resets the step height back to the default. I'll release a patch as soon as possible

**Comment by SiliconAshes** [comment]
Thank you very much for the fix!  I'll try it out now.
