### ISSUE TITLE
[Suggestion] Cosmetic Toggles

### ISSUE THREAD

**Issue by AmyMialee** [ochotonida/artifacts#97]
It would be nice to have some way to disable the artifacts visually, even through an extra options menu like the skin menu. 
Ideally not as a config option since I'd like to disable it on myself but I don't want to disable it on other people too.

**Comment by ochotonida** [comment]
Curios already provides buttons to toggle cosmetics, I'm assuming this is a fabric-specific request? If it is, you should put it on the [issue tracker of the fabric version](https://github.com/florensie/artifacts-fabric/issues) 🙂
